CREATE TABLE COMTECOPSEQ
(
	TABLE_NAME            VARCHAR(20) NOT NULL,
	NEXT_ID               NUMERIC(30) NULL,
	 PRIMARY KEY (TABLE_NAME)
)
;

CREATE UNIQUE INDEX COMTECOPSEQ_PK ON COMTECOPSEQ
(
	TABLE_NAME
)
;



CREATE TABLE COMTCCMMNCLCODE
(
	CL_CODE               CHAR(3) NOT NULL,
	CL_CODE_NM            VARCHAR(60) NULL,
	CL_CODE_DC            VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CL_CODE)
)
;

CREATE UNIQUE INDEX COMTCCMMNCLCODE_PK ON COMTCCMMNCLCODE
(
	CL_CODE
)
;



CREATE TABLE COMTCCMMNCODE
(
	CODE_ID               VARCHAR(6) NOT NULL,
	CODE_ID_NM            VARCHAR(60) NULL,
	CODE_ID_DC            VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	CL_CODE               CHAR(3) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CODE_ID),
	FOREIGN KEY COMTCCMMNCODE_FK1 (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE)
)
;

CREATE UNIQUE INDEX COMTCCMMNCODE_PK ON COMTCCMMNCODE
(
	CODE_ID
)
;
CREATE INDEX COMTCCMMNCODE_i01 ON COMTCCMMNCODE
(
	CL_CODE
)
;



CREATE TABLE COMTCCMMNDETAILCODE
(
	CODE_ID               VARCHAR(6) NOT NULL,
	CODE                  VARCHAR(15) NOT NULL,
	CODE_NM               VARCHAR(60) NULL,
	CODE_DC               VARCHAR(200) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CODE_ID,CODE),
	FOREIGN KEY COMTCCMMNDETAILCODE_FK1 (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
)
;

CREATE UNIQUE INDEX COMTCCMMNDETAILCODE_PK ON COMTCCMMNDETAILCODE
(
	CODE_ID,
	CODE
)
;
CREATE INDEX COMTCCMMNDETAILCODE_i01 ON COMTCCMMNDETAILCODE
(
	CODE_ID
)
;



CREATE TABLE COMTNAUTHORGROUPINFO
(
	GROUP_ID              CHAR(20) NOT NULL,
	GROUP_NM              VARCHAR(60) NOT NULL,
	GROUP_CREAT_DE        CHAR(20) NOT NULL,
	GROUP_DC              VARCHAR(100) NULL,
	 PRIMARY KEY (GROUP_ID)
)
;

CREATE UNIQUE INDEX COMTNAUTHORGROUPINFO_PK ON COMTNAUTHORGROUPINFO
(
	GROUP_ID
)
;



CREATE TABLE COMTNGNRLMBER
(
	MBER_ID               VARCHAR(20) NOT NULL,
	PASSWORD              VARCHAR(200) NOT NULL,
	PASSWORD_HINT         VARCHAR(100) NULL,
	PASSWORD_CNSR         VARCHAR(100) NULL,
	IHIDNUM               VARCHAR(200) NULL,
	MBER_NM               VARCHAR(50) NOT NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	ADRES                 VARCHAR(100) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	MBER_STTUS            VARCHAR(15) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	END_TELNO             VARCHAR(4) NOT NULL,
	MBTLNUM               VARCHAR(20) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	MBER_FXNUM            VARCHAR(20) NULL,
	MBER_EMAIL_ADRES      VARCHAR(50) NULL,
	MIDDLE_TELNO          VARCHAR(4) NOT NULL,
	SBSCRB_DE             DATETIME NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	 PRIMARY KEY (MBER_ID),
	FOREIGN KEY COMTNGNRLMBER_FK1 (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNGNRLMBER_PK ON COMTNGNRLMBER
(
	MBER_ID
)
;
CREATE INDEX COMTNGNRLMBER_i01 ON COMTNGNRLMBER
(
	GROUP_ID
)
;



CREATE TABLE COMTNORGNZTINFO
(
	ORGNZT_ID             CHAR(20) NOT NULL,
	ORGNZT_NM             VARCHAR(20) NOT NULL,
	ORGNZT_DC             VARCHAR(100) NULL,
	 PRIMARY KEY (ORGNZT_ID)
)
;

CREATE UNIQUE INDEX COMTNORGNZTINFO_PK ON COMTNORGNZTINFO
(
	ORGNZT_ID
)
;



CREATE TABLE COMTNEMPLYRINFO
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	ORGNZT_ID             CHAR(20) NULL,
	USER_NM               VARCHAR(60) NOT NULL,
	PASSWORD              VARCHAR(200) NOT NULL,
	EMPL_NO               VARCHAR(20) NULL,
	IHIDNUM               VARCHAR(200) NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	BRTHDY                CHAR(20) NULL,
	FXNUM                 VARCHAR(20) NULL,
	HOUSE_ADRES           VARCHAR(100) NOT NULL,
	PASSWORD_HINT         VARCHAR(100) NOT NULL,
	PASSWORD_CNSR         VARCHAR(100) NOT NULL,
	HOUSE_END_TELNO       VARCHAR(4) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	OFFM_TELNO            VARCHAR(20) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	OFCPS_NM              VARCHAR(60) NULL,
	HOUSE_MIDDLE_TELNO    VARCHAR(4) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	PSTINST_CODE          CHAR(8) NULL,
	EMPLYR_STTUS_CODE     CHAR(1) NOT NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	CRTFC_DN_VALUE        VARCHAR(100) NULL,
	SBSCRB_DE             DATETIME NULL,
	 PRIMARY KEY (EMPLYR_ID),
	FOREIGN KEY COMTNEMPLYRINFO_FK2 (ORGNZT_ID) REFERENCES COMTNORGNZTINFO(ORGNZT_ID)
		ON DELETE SET NULL,
	FOREIGN KEY COMTNEMPLYRINFO_FK1 (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNEMPLYRINFO_PK ON COMTNEMPLYRINFO
(
	EMPLYR_ID
)
;
CREATE INDEX COMTNEMPLYRINFO_i01 ON COMTNEMPLYRINFO
(
	ORGNZT_ID
)
;
CREATE INDEX COMTNEMPLYRINFO_i02 ON COMTNEMPLYRINFO
(
	GROUP_ID
)
;



CREATE TABLE COMTNENTRPRSMBER
(
	ENTRPRS_MBER_ID       VARCHAR(20) NOT NULL,
	ENTRPRS_SE_CODE       CHAR(8) NULL,
	BIZRNO                VARCHAR(10) NULL,
	JURIRNO               VARCHAR(13) NULL,
	CMPNY_NM              VARCHAR(60) NOT NULL,
	CXFC                  VARCHAR(50) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	ADRES                 VARCHAR(100) NOT NULL,
	ENTRPRS_MIDDLE_TELNO  VARCHAR(4) NOT NULL,
	FXNUM                 VARCHAR(20) NULL,
	INDUTY_CODE           CHAR(1) NULL,
	APPLCNT_NM            VARCHAR(50) NOT NULL,
	APPLCNT_IHIDNUM       VARCHAR(200) NULL,
	SBSCRB_DE             DATETIME NULL,
	ENTRPRS_MBER_STTUS    VARCHAR(15) NULL,
	ENTRPRS_MBER_PASSWORD  VARCHAR(200) NULL,
	ENTRPRS_MBER_PASSWORD_HINT  VARCHAR(100) NOT NULL,
	ENTRPRS_MBER_PASSWORD_CNSR  VARCHAR(100) NOT NULL,
	GROUP_ID              CHAR(20) NULL,
	DETAIL_ADRES          VARCHAR(100) NULL,
	ENTRPRS_END_TELNO     VARCHAR(4) NOT NULL,
	AREA_NO               VARCHAR(4) NOT NULL,
	APPLCNT_EMAIL_ADRES   VARCHAR(50) NOT NULL,
	ESNTL_ID              CHAR(20) NOT NULL,
	 PRIMARY KEY (ENTRPRS_MBER_ID),
	FOREIGN KEY COMTNENTRPRSMBER_FK1 (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNENTRPRSMBER_PK ON COMTNENTRPRSMBER
(
	ENTRPRS_MBER_ID
)
;
CREATE INDEX COMTNENTRPRSMBER_i01 ON COMTNENTRPRSMBER
(
	GROUP_ID
)
;



CREATE TABLE COMTNFILE
(
	ATCH_FILE_ID          CHAR(20) NOT NULL,
	CREAT_DT              DATETIME NOT NULL,
	USE_AT                CHAR(1) NULL,
	 PRIMARY KEY (ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTNFILE_PK ON COMTNFILE
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTNFILEDETAIL
(
	ATCH_FILE_ID          CHAR(20) NOT NULL,
	FILE_SN               NUMERIC(10) NOT NULL,
	FILE_STRE_COURS       VARCHAR(2000) NOT NULL,
	STRE_FILE_NM          VARCHAR(255) NOT NULL,
	ORIGNL_FILE_NM        VARCHAR(255) NULL,
	FILE_EXTSN            VARCHAR(20) NOT NULL,
	FILE_CN               MEDIUMTEXT NULL,
	FILE_SIZE             NUMERIC(8) NULL,
	 PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
	FOREIGN KEY COMTNFILEDETAIL_FK1 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTNFILEDETAIL_PK ON COMTNFILEDETAIL
(
	ATCH_FILE_ID,
	FILE_SN
)
;
CREATE INDEX COMTNFILEDETAIL_i01 ON COMTNFILEDETAIL
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTHEMAILDSPTCHMANAGE
(
	MSSAGE_ID             VARCHAR(20) NOT NULL,
	EMAIL_CN              MEDIUMTEXT NULL,
	SNDR                  VARCHAR(50) NOT NULL,
	RCVER                 VARCHAR(50) NOT NULL,
	SJ                    VARCHAR(60) NOT NULL,
	SNDNG_RESULT_CODE     CHAR(1) NULL,
	DSPTCH_DT             CHAR(20) NOT NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	 PRIMARY KEY (MSSAGE_ID),
	FOREIGN KEY COMTHEMAILDSPTCHMANAGE_FK1 (SNDR) REFERENCES COMTNEMPLYRINFO(EMPLYR_ID),
	FOREIGN KEY COMTHEMAILDSPTCHMANAGE_FK2 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTHEMAILDSPTCHMANAGE_PK ON COMTHEMAILDSPTCHMANAGE
(
	MSSAGE_ID
)
;
CREATE INDEX COMTHEMAILDSPTCHMANAGE_i01 ON COMTHEMAILDSPTCHMANAGE
(
	SNDR
)
;
CREATE INDEX COMTHEMAILDSPTCHMANAGE_i02 ON COMTHEMAILDSPTCHMANAGE
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTNTMPLATINFO
(
	TMPLAT_ID             CHAR(20) NOT NULL,
	TMPLAT_NM             VARCHAR(255) NULL,
	TMPLAT_COURS          VARCHAR(2000) NULL,
	USE_AT                CHAR(1) NULL,
	TMPLAT_SE_CODE        CHAR(6) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (TMPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNTMPLATINFO_PK ON COMTNTMPLATINFO
(
	TMPLAT_ID
)
;



CREATE TABLE COMTNRESTDE
(
	RESTDE_NO             NUMERIC(6) NOT NULL,
	RESTDE                CHAR(8) NULL,
	RESTDE_NM             VARCHAR(60) NULL,
	RESTDE_DC             VARCHAR(200) NULL,
	RESTDE_SE_CODE        VARCHAR(2) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (RESTDE_NO)
)
;

CREATE UNIQUE INDEX COMTNRESTDE_PK ON COMTNRESTDE
(
	RESTDE_NO
)
;





CREATE  VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
		SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNGNRLMBER
		
	UNION ALL
		SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
		FROM COMTNEMPLYRINFO
	UNION ALL
		SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNENTRPRSMBER 
ORDER BY ESNTL_ID;


CREATE TABLE COMTNBBSMASTER
(
	BBS_ID                CHAR(20) NOT NULL,
	BBS_NM                VARCHAR(255) NOT NULL,
	BBS_INTRCN            VARCHAR(2400) NULL,
	BBS_TY_CODE           CHAR(6) NOT NULL,
	BBS_ATTRB_CODE        CHAR(6) NOT NULL,
	REPLY_POSBL_AT        CHAR(1) NULL,
	FILE_ATCH_POSBL_AT    CHAR(1) NOT NULL,
	ATCH_POSBL_FILE_NUMBER  NUMERIC(2) NOT NULL,
	ATCH_POSBL_FILE_SIZE  NUMERIC(8) NULL,
	USE_AT                CHAR(1) NOT NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBSMASTER_PK ON COMTNBBSMASTER
(
	BBS_ID
)
;



CREATE TABLE COMTNBBSUSE
(
	BBS_ID                CHAR(20) NOT NULL,
	TRGET_ID              CHAR(20) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (BBS_ID,TRGET_ID),
	FOREIGN KEY COMTNBBSUSE_FK1 (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBSUSE_PK ON COMTNBBSUSE
(
	BBS_ID,
	TRGET_ID
)
;
CREATE INDEX COMTNBBSUSE_i01 ON COMTNBBSUSE
(
	BBS_ID
)
;



CREATE TABLE COMTNBBS
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	NTT_NO                NUMERIC(20) NULL,
	NTT_SJ                VARCHAR(2000) NULL,
	NTT_CN                MEDIUMTEXT NULL,
	ANSWER_AT             CHAR(1) NULL,
	PARNTSCTT_NO          NUMERIC(10) NULL,
	ANSWER_LC             NUMERIC(8) NULL,
	SORT_ORDR             NUMERIC(8) NULL,
	RDCNT                 NUMERIC(10) NULL,
	USE_AT                CHAR(1) NOT NULL,
	NTCE_BGNDE            CHAR(20) NULL,
	NTCE_ENDDE            CHAR(20) NULL,
	NTCR_ID               VARCHAR(20) NULL,
	NTCR_NM               VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (NTT_ID,BBS_ID),
	FOREIGN KEY COMTNBBS_FK1 (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBS_PK ON COMTNBBS
(
	NTT_ID,
	BBS_ID
)
;
CREATE INDEX COMTNBBS_i01 ON COMTNBBS
(
	BBS_ID
)
;



CREATE TABLE COMTNCMMNTY
(
	CMMNTY_ID             CHAR(20) NOT NULL,
	CMMNTY_NM             VARCHAR(255) NOT NULL,
	CMMNTY_INTRCN         VARCHAR(2400) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCMMNTY_PK ON COMTNCMMNTY
(
	CMMNTY_ID
)
;



CREATE TABLE COMTNCLUB
(
	CLB_ID                CHAR(20) NOT NULL,
	CMMNTY_ID             CHAR(20) NOT NULL,
	CLB_NM                VARCHAR(255) NOT NULL,
	CLB_INTRCN            VARCHAR(2400) NULL,
	USE_AT                CHAR(1) NOT NULL,
	REGIST_SE_CODE        CHAR(6) NULL,
	TMPLAT_ID             CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CLB_ID,CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCLUB_PK ON COMTNCLUB
(
	CLB_ID,
	CMMNTY_ID
)
;



CREATE TABLE COMTNBBSMASTEROPTN
(
	BBS_ID                CHAR(20) NOT NULL,
	ANSWER_AT             CHAR(1) NOT NULL,
	STSFDG_AT             CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNBBSMASTEROPTN_PK ON COMTNBBSMASTEROPTN
(
	BBS_ID
)
;



CREATE TABLE COMTNCOMMENT
(
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	ANSWER_NO             NUMERIC(20) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	ANSWER                VARCHAR(200) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	 PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
	FOREIGN KEY COMTNCOMMENT_FK1 (NTT_ID,BBS_ID) REFERENCES COMTNBBS(NTT_ID,BBS_ID)
)
;

CREATE UNIQUE INDEX COMTNCOMMENT_PK ON COMTNCOMMENT
(
	NTT_ID,
	BBS_ID,
	ANSWER_NO
)
;
CREATE INDEX COMTNCOMMENT_i01 ON COMTNCOMMENT
(
	NTT_ID,
	BBS_ID
)
;



CREATE TABLE COMTNSCRAP
(
	SCRAP_ID              CHAR(20) NOT NULL,
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	SCRAP_NM              VARCHAR(100) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (SCRAP_ID)
)
;

CREATE UNIQUE INDEX COMTNSCRAP_PK ON COMTNSCRAP
(
	SCRAP_ID
)
;



CREATE TABLE COMTNSTSFDG
(
	STSFDG_NO             NUMERIC(20) NOT NULL,
	NTT_ID                NUMERIC(20) NOT NULL,
	BBS_ID                CHAR(20) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	PASSWORD              VARCHAR(200) NULL,
	STSFDG                NUMERIC(1) NOT NULL,
	STSFDG_CN             VARCHAR(200) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (STSFDG_NO)
)
;

CREATE UNIQUE INDEX COMTNSTSFDG_PK ON COMTNSTSFDG
(
	STSFDG_NO
)
;



CREATE TABLE COMTHCONFMHISTORY
(
	CONFM_NO              NUMERIC(8) NOT NULL,
	CONFM_RQESTER_ID      VARCHAR(20) NOT NULL,
	CONFMER_ID            VARCHAR(20) NULL,
	CONFM_DE              CHAR(20) NULL,
	CONFM_TY_CODE         CHAR(4) NOT NULL,
	CONFM_STTUS_CODE      CHAR(4) NOT NULL,
	OPERT_TY_CODE         CHAR(4) NULL,
	OPERT_ID              VARCHAR(20) NULL,
	TRGET_JOB_TY_CODE     CHAR(3) NULL,
	TRGET_JOB_ID          CHAR(20) NULL,
	 PRIMARY KEY (CONFM_NO)
)
;

CREATE UNIQUE INDEX COMTHCONFMHISTORY_PK ON COMTHCONFMHISTORY
(
	CONFM_NO
)
;



CREATE TABLE COMTNCMMNTYUSER
(
	CMMNTY_ID             CHAR(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	MNGR_AT               CHAR(1) NOT NULL,
	SBSCRB_DE             DATETIME NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (CMMNTY_ID,EMPLYR_ID),
	FOREIGN KEY COMTNCMMNTYUSER_FK1 (CMMNTY_ID) REFERENCES COMTNCMMNTY(CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCMMNTYUSER_PK ON COMTNCMMNTYUSER
(
	CMMNTY_ID,
	EMPLYR_ID
)
;
CREATE INDEX COMTNCMMNTYUSER_i01 ON COMTNCMMNTYUSER
(
	CMMNTY_ID
)
;



CREATE TABLE COMTNCLUBUSER
(
	CLB_ID                CHAR(20) NOT NULL,
	CMMNTY_ID             CHAR(20) NOT NULL,
	OPRTR_AT              CHAR(1) NOT NULL,
	SBSCRB_DE             DATETIME NULL,
	SECSN_DE              CHAR(20) NULL,
	USE_AT                CHAR(1) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	 PRIMARY KEY (CLB_ID,CMMNTY_ID,EMPLYR_ID),
	FOREIGN KEY COMTNCLUBUSER_FK1 (CLB_ID,CMMNTY_ID) REFERENCES COMTNCLUB(CLB_ID,CMMNTY_ID)
)
;

CREATE UNIQUE INDEX COMTNCLUBUSER_PK ON COMTNCLUBUSER
(
	CLB_ID,
	CMMNTY_ID,
	EMPLYR_ID
)
;
CREATE INDEX COMTNCLUBUSER_i01 ON COMTNCLUBUSER
(
	CLB_ID,
	CMMNTY_ID
)
;



CREATE TABLE COMTNMTGINFO
(
	MTG_ID                CHAR(20) NOT NULL,
	MTG_NM                VARCHAR(255) NULL,
	MTG_MTR_CN            VARCHAR(1000) NULL,
	MTG_SN                NUMERIC(10) NULL,
	MTG_CO                NUMERIC(5) NULL,
	MTG_DE                CHAR(20) NULL,
	MTG_PLACE             VARCHAR(255) NULL,
	MTG_BEGIN_TM          VARCHAR(14) NULL,
	MTG_END_TM            VARCHAR(14) NULL,
	CLSDR_MTG_AT          CHAR(1) NULL,
	READNG_BGNDE          CHAR(20) NULL,
	READNG_AT             CHAR(1) NULL,
	MTG_RESULT_CN         VARCHAR(1000) NULL,
	MTG_RESULT_ENNC       CHAR(1) NULL,
	ETC_MATTER            VARCHAR(1000) NULL,
	MNGT_DEPT_ID          VARCHAR(20) NULL,
	MNAER_ID              VARCHAR(20) NULL,
	MNAER_DEPT_ID         VARCHAR(20) NULL,
	MTG_AT                CHAR(1) NULL,
	NONATDRN_CO           NUMERIC(10) NULL,
	ATDRN_CO              NUMERIC(10) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (MTG_ID)
)
;

CREATE UNIQUE INDEX COMTNMTGINFO_PK ON COMTNMTGINFO
(
	MTG_ID
)
;



CREATE TABLE COMTNSCHDULINFO
(
	SCHDUL_ID             CHAR(20) NOT NULL,
	SCHDUL_SE             CHAR(1) NULL,
	SCHDUL_DEPT_ID        VARCHAR(20) NULL,
	SCHDUL_KND_CODE       CHAR(1) NULL,
	SCHDUL_BGNDE          CHAR(20) NULL,
	SCHDUL_ENDDE          CHAR(20) NULL,
	SCHDUL_NM             VARCHAR(255) NULL,
	SCHDUL_CN             VARCHAR(2500) NULL,
	SCHDUL_PLACE          VARCHAR(255) NULL,
	SCHDUL_IPCR_CODE      CHAR(1) NULL,
	SCHDUL_CHARGER_ID     VARCHAR(20) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	REPTIT_SE_CODE        CHAR(1) NULL,
	 PRIMARY KEY (SCHDUL_ID)
)
;

CREATE UNIQUE INDEX COMTNSCHDULINFO_PK ON COMTNSCHDULINFO
(
	SCHDUL_ID
)
;



CREATE TABLE COMTNDIARYINFO
(
	SCHDUL_ID             CHAR(20) NOT NULL,
	DIARY_ID              CHAR(20) NOT NULL,
	DIARY_PROGRSRT        NUMERIC(3) NULL,
	DIARY_NM              VARCHAR(255) NULL,
	DRCT_MATTER           VARCHAR(2500) NULL,
	PARTCLR_MATTER        VARCHAR(2500) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (SCHDUL_ID,DIARY_ID),
	FOREIGN KEY COMTNDIARYINFO_FK1 (SCHDUL_ID) REFERENCES COMTNSCHDULINFO(SCHDUL_ID)
)
;

CREATE UNIQUE INDEX COMTNDIARYINFO_PK ON COMTNDIARYINFO
(
	SCHDUL_ID,
	DIARY_ID
)
;
CREATE INDEX COMTNDIARYINFO_i01 ON COMTNDIARYINFO
(
	SCHDUL_ID
)
;



CREATE TABLE COMTNINDVDLPGECNTNTS
(
	CNTNTS_ID             VARCHAR(20) NOT NULL,
	CNTNTS_NM             VARCHAR(100) NOT NULL,
	CNTC_URL              VARCHAR(255) NOT NULL,
	CNTNTS_USE_AT         CHAR(1) NOT NULL,
	CNTNTS_LINK_URL       VARCHAR(1000) NULL,
	CNTNTS_DC             VARCHAR(250) NULL,
	 PRIMARY KEY (CNTNTS_ID)
)
;

CREATE UNIQUE INDEX COMTNINDVDLPGECNTNTS_PK ON COMTNINDVDLPGECNTNTS
(
	CNTNTS_ID
)
;



CREATE TABLE COMTNINDVDLPGEESTBS
(
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	UPEND_IMAGE           VARCHAR(1024) NULL,
	TITLEBAR_COLOR        CHAR(7) NULL,
	ALGN_MTHD             CHAR(1) NULL,
	ALGN_CO               NUMERIC(10) NULL,
	 PRIMARY KEY (EMPLYR_ID)
)
;

CREATE UNIQUE INDEX COMTNINDVDLPGEESTBS_PK ON COMTNINDVDLPGEESTBS
(
	EMPLYR_ID
)
;



CREATE TABLE COMTNCNTNTSLIST
(
	CNTNTS_ID             VARCHAR(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	 PRIMARY KEY (CNTNTS_ID,EMPLYR_ID),
	FOREIGN KEY COMTNCNTNTSLIST_FK1 (CNTNTS_ID) REFERENCES COMTNINDVDLPGECNTNTS(CNTNTS_ID),
	FOREIGN KEY COMTNCNTNTSLIST_FK2 (EMPLYR_ID) REFERENCES COMTNINDVDLPGEESTBS(EMPLYR_ID)
)
;

CREATE UNIQUE INDEX COMTNCNTNTSLIST_PK ON COMTNCNTNTSLIST
(
	CNTNTS_ID,
	EMPLYR_ID
)
;
CREATE INDEX COMTNCNTNTSLIST_i01 ON COMTNCNTNTSLIST
(
	CNTNTS_ID
)
;
CREATE INDEX COMTNCNTNTSLIST_i02 ON COMTNCNTNTSLIST
(
	EMPLYR_ID
)
;



CREATE TABLE COMTNSTPLATINFO
(
	USE_STPLAT_ID         CHAR(20) NOT NULL,
	USE_STPLAT_NM         VARCHAR(100) NULL,
	USE_STPLAT_CN         MEDIUMTEXT NULL,
	INFO_PROVD_AGRE_CN    MEDIUMTEXT NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (USE_STPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNSTPLATINFO_PK ON COMTNSTPLATINFO
(
	USE_STPLAT_ID
)
;



CREATE TABLE COMTNHPCMINFO
(
	HPCM_ID               CHAR(20) NOT NULL,
	HPCM_SE_CODE          CHAR(1) NULL,
	HPCM_DFN              VARCHAR(1000) NULL,
	HPCM_DC               VARCHAR(2500) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (HPCM_ID)
)
;

CREATE UNIQUE INDEX COMTNHPCMINFO_PK ON COMTNHPCMINFO
(
	HPCM_ID
)
;



CREATE TABLE COMTNWORDDICARYINFO
(
	WORD_ID               CHAR(20) NOT NULL,
	WORD_NM               VARCHAR(255) NULL,
	ENG_NM                VARCHAR(60) NULL,
	WORD_DC               VARCHAR(4000) NULL,
	SYNONM                VARCHAR(100) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (WORD_ID)
)
;

CREATE UNIQUE INDEX COMTNWORDDICARYINFO_PK ON COMTNWORDDICARYINFO
(
	WORD_ID
)
;



CREATE TABLE COMTNFAQINFO
(
	FAQ_ID                CHAR(20) NOT NULL,
	QESTN_SJ              VARCHAR(255) NULL,
	QESTN_CN              VARCHAR(2500) NULL,
	ANSWER_CN             VARCHAR(2500) NULL,
	RDCNT                 NUMERIC(10) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	QNA_PROCESS_STTUS_CODE  CHAR(1) NULL,
	 PRIMARY KEY (FAQ_ID),
	FOREIGN KEY COMTNFAQINFO_FK1 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
)
;

CREATE UNIQUE INDEX COMTNFAQINFO_PK ON COMTNFAQINFO
(
	FAQ_ID
)
;
CREATE INDEX COMTNFAQINFO_i01 ON COMTNFAQINFO
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTNQAINFO
(
	QA_ID                 CHAR(20) NOT NULL,
	QESTN_SJ              VARCHAR(255) NULL,
	QESTN_CN              VARCHAR(2500) NULL,
	WRITNG_DE             CHAR(20) NULL,
	RDCNT                 NUMERIC(10) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	QNA_PROCESS_STTUS_CODE  CHAR(1) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	ANSWER_CN             VARCHAR(2500) NULL,
	WRITNG_PASSWORD       VARCHAR(20) NULL,
	ANSWER_DE             CHAR(20) NULL,
	EMAIL_ANSWER_AT       CHAR(1) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	 PRIMARY KEY (QA_ID)
)
;

CREATE UNIQUE INDEX COMTNQAINFO_PK ON COMTNQAINFO
(
	QA_ID
)
;

CREATE TABLE COMTNADBKMANAGE
(
	ADBK_ID               CHAR(20) NOT NULL,
	ADBK_NM               VARCHAR(50) NOT NULL,
	OTHBC_SCOPE           VARCHAR(20) NOT NULL,
	USE_AT                CHAR(1) NOT NULL,
	WRTER_ID              VARCHAR(20) NULL,
	TRGET_ORGNZT_ID       CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (ADBK_ID)
)
;



CREATE UNIQUE INDEX COMTNADBKMANAGE_PK ON COMTNADBKMANAGE
(
	ADBK_ID
)
;

CREATE TABLE COMTNADBK
(
	EMPLYR_ID             VARCHAR(20) NULL,
	NCRD_ID               CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	ADBK_CONSTNT_ID       CHAR(20) NOT NULL,
	NM                    VARCHAR(50) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	MBTLNUM               VARCHAR(20) NULL,
	FXNUM                 VARCHAR(20) NULL,
	OFFM_TELNO            VARCHAR(20) NULL,
	HOUSE_TELNO           VARCHAR(20) NULL,
	ADBK_ID               CHAR(20) NOT NULL,
	 PRIMARY KEY (ADBK_CONSTNT_ID,ADBK_ID),
	FOREIGN KEY COMTNADBK_FK1 (ADBK_ID) REFERENCES COMTNADBKMANAGE(ADBK_ID)
		ON DELETE CASCADE
)
;



CREATE UNIQUE INDEX COMTNADBK_PK ON COMTNADBK
(
	ADBK_CONSTNT_ID,
	ADBK_ID
)
;



CREATE INDEX COMTNADBK_i01 ON COMTNADBK
(
	ADBK_ID
)
;

CREATE TABLE COMTNRECOMENDSITEINFO
(
	RECOMEND_SITE_ID      CHAR(20) NOT NULL,
	RECOMEND_SITE_NM      VARCHAR(100) NULL,
	RECOMEND_SITE_URL     VARCHAR(255) NULL,
	RECOMEND_SITE_DC      VARCHAR(1000) NULL,
	RECOMEND_RESN_CN      VARCHAR(1000) NULL,
	RECOMEND_CONFM_AT     CHAR(1) NULL,
	CONFM_DE              CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (RECOMEND_SITE_ID)
)
;



CREATE UNIQUE INDEX COMTNRECOMENDSITEINFO_PK ON COMTNRECOMENDSITEINFO
(
	RECOMEND_SITE_ID
)
;

CREATE TABLE COMTNROLEINFO
(
	ROLE_CODE             VARCHAR(50) NOT NULL,
	ROLE_NM               VARCHAR(60) NOT NULL,
	ROLE_PTTRN            VARCHAR(300) NULL,
	ROLE_DC               VARCHAR(200) NULL,
	ROLE_TY               VARCHAR(80) NULL,
	ROLE_SORT             VARCHAR(10) NULL,
	ROLE_CREAT_DE         CHAR(20) NOT NULL,
	 PRIMARY KEY (ROLE_CODE)
)
;



CREATE UNIQUE INDEX COMTNROLEINFO_PK ON COMTNROLEINFO
(
	ROLE_CODE
)
;



CREATE TABLE COMTNAUTHORINFO
(
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	AUTHOR_NM             VARCHAR(60) NOT NULL,
	AUTHOR_DC             VARCHAR(200) NULL,
	AUTHOR_CREAT_DE       CHAR(20) NOT NULL,
	 PRIMARY KEY (AUTHOR_CODE)
)
;

CREATE UNIQUE INDEX COMTNAUTHORINFO_PK ON COMTNAUTHORINFO
(
	AUTHOR_CODE
)
;




CREATE TABLE COMTNAUTHORROLERELATE
(
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	ROLE_CODE             VARCHAR(50) NOT NULL,
	CREAT_DT              DATETIME NULL,
	 PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
	FOREIGN KEY COMTNAUTHORROLERELATE_FK1 (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNAUTHORROLERELATE_FK2 (ROLE_CODE) REFERENCES COMTNROLEINFO(ROLE_CODE)
		ON DELETE CASCADE
)
;



CREATE UNIQUE INDEX COMTNAUTHORROLERELATE_PK ON COMTNAUTHORROLERELATE
(
	AUTHOR_CODE,
	ROLE_CODE
)
;



CREATE INDEX COMTNAUTHORROLERELATE_i01 ON COMTNAUTHORROLERELATE
(
	AUTHOR_CODE
)
;



CREATE INDEX COMTNAUTHORROLERELATE_i02 ON COMTNAUTHORROLERELATE
(
	ROLE_CODE
)
;



CREATE TABLE COMTNADMINISTRATIONWORD
(
	ADMINIST_WORD_ID      CHAR(20) NOT NULL,
	ADMINIST_WORD_NM      VARCHAR(255) NULL,
	ADMINIST_WORD_ENG_NM  VARCHAR(255) NULL,
	ADMINIST_WORD_ABRV_NM  VARCHAR(255) NULL,
	THEMA_RELM            VARCHAR(255) NULL,
	WORD_SE               VARCHAR(255) NULL,
	RELATE_STD_WORD       VARCHAR(255) NULL,
	ADMINIST_WORD_DFN     VARCHAR(2500) NULL,
	ADMINIST_WORD_DC      VARCHAR(4000) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (ADMINIST_WORD_ID)
)
;

CREATE UNIQUE INDEX COMTNADMINISTRATIONWORD_PK ON COMTNADMINISTRATIONWORD
(
	ADMINIST_WORD_ID
)
;



CREATE TABLE COMTNONLINEMANUAL
(
	ONLINE_MNL_ID         CHAR(20) NOT NULL,
	ONLINE_MNL_SE_CODE    CHAR(3) NULL,
	ONLINE_MNL_DFN        MEDIUMTEXT NULL,
	ONLINE_MNL_DC         MEDIUMTEXT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	ONLINE_MNL_NM         VARCHAR(255) NULL,
	 PRIMARY KEY (ONLINE_MNL_ID)
)
;

CREATE UNIQUE INDEX COMTNONLINEMANUAL_PK ON COMTNONLINEMANUAL
(
	ONLINE_MNL_ID
)
;



CREATE TABLE COMTNCNSLTLIST
(
	CNSLT_ID              CHAR(20) NOT NULL,
	CNSLT_SJ              VARCHAR(255) NULL,
	OTHBC_AT              CHAR(1) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	CNSLT_CN              VARCHAR(2500) NULL,
	MANAGT_CN             VARCHAR(2500) NULL,
	MANAGT_DE             CHAR(20) NULL,
	RDCNT                 NUMERIC(10) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	FRST_MBTLNUM          VARCHAR(4) NULL,
	MIDDLE_MBTLNUM        VARCHAR(4) NULL,
	END_MBTLNUM           VARCHAR(4) NULL,
	WRITNG_DE             CHAR(20) NULL,
	WRTER_NM              VARCHAR(20) NULL,
	EMAIL_ANSWER_AT       CHAR(1) NULL,
	QNA_PROCESS_STTUS_CODE  CHAR(1) NULL,
	WRITNG_PASSWORD       VARCHAR(20) NULL,
	 PRIMARY KEY (CNSLT_ID)
)
;

CREATE UNIQUE INDEX COMTNCNSLTLIST_PK ON COMTNCNSLTLIST
(
	CNSLT_ID
)
;



CREATE TABLE COMTNQUSTNRTMPLAT
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QUSTNR_TMPLAT_TY      VARCHAR(100) NULL,
	QUSTNR_TMPLAT_DC      VARCHAR(2000) NULL,
	QUSTNR_TMPLAT_PATH_NM  VARCHAR(100) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	QUSTNR_TMPLAT_IMAGE_INFO  BLOB NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNQUSTNRTMPLAT_PK ON COMTNQUSTNRTMPLAT
(
	QUSTNR_TMPLAT_ID
)
;



CREATE TABLE COMTNQESTNRINFO
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_SJ             VARCHAR(255) NULL,
	QUSTNR_PURPS          VARCHAR(1000) NULL,
	QUSTNR_WRITNG_GUIDANCE_CN  VARCHAR(2000) NULL,
	QUSTNR_TRGET          VARCHAR(1000) NULL,
	QUSTNR_BGNDE          CHAR(20) NULL,
	QUSTNR_ENDDE          CHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
	FOREIGN KEY COMTNQESTNRINFO_FK1 (QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRTMPLAT(QUSTNR_TMPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNQESTNRINFO_PK ON COMTNQESTNRINFO
(
	QUSTNR_TMPLAT_ID,
	QESTNR_ID
)
;
CREATE INDEX COMTNQESTNRINFO_i01 ON COMTNQESTNRINFO
(
	QUSTNR_TMPLAT_ID
)
;



CREATE TABLE COMTNQUSTNRRESPONDINFO
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_RESPOND_ID     CHAR(20) NOT NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	OCCP_TY_CODE          CHAR(1) NULL,
	RESPOND_NM            VARCHAR(50) NULL,
	BRTHDY                CHAR(20) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
	FOREIGN KEY COMTNQUSTNRRESPONDINFO_FK1 (QUSTNR_TMPLAT_ID,QESTNR_ID) REFERENCES COMTNQESTNRINFO(QUSTNR_TMPLAT_ID,QESTNR_ID)
)
;

CREATE UNIQUE INDEX COMTNQUSTNRRESPONDINFO_PK ON COMTNQUSTNRRESPONDINFO
(
	QUSTNR_TMPLAT_ID,
	QESTNR_ID,
	QUSTNR_RESPOND_ID
)
;
CREATE INDEX COMTNQUSTNRRESPONDINFO_i01 ON COMTNQUSTNRRESPONDINFO
(
	QESTNR_ID,
	QUSTNR_TMPLAT_ID
)
;



CREATE TABLE COMTNQUSTNRQESITM
(
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_QESITM_ID      CHAR(20) NOT NULL,
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTN_SN              NUMERIC(10) NULL,
	QESTN_TY_CODE         CHAR(1) NULL,
	QESTN_CN              VARCHAR(2500) NULL,
	MXMM_CHOISE_CO        NUMERIC(5) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	 PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
	FOREIGN KEY COMTNQUSTNRQESITM_FK1 (QUSTNR_TMPLAT_ID,QESTNR_ID) REFERENCES COMTNQESTNRINFO(QUSTNR_TMPLAT_ID,QESTNR_ID)
)
;

CREATE UNIQUE INDEX COMTNQUSTNRQESITM_PK ON COMTNQUSTNRQESITM
(
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_TMPLAT_ID
)
;
CREATE INDEX COMTNQUSTNRQESITM_i02 ON COMTNQUSTNRQESITM
(
	QESTNR_ID,
	QUSTNR_TMPLAT_ID
)
;



CREATE TABLE COMTNQUSTNRRSPNSRESULT
(
	QUSTNR_RSPNS_RESULT_ID  CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_QESITM_ID      CHAR(20) NOT NULL,
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	RESPOND_ANSWER_CN     VARCHAR(1000) NULL,
	ETC_ANSWER_CN         VARCHAR(1000) NULL,
	RESPOND_NM            VARCHAR(50) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	QUSTNR_IEM_ID         VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
	FOREIGN KEY COMTNQUSTNRRSPNSRESULT_FK1 (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRQESITM(QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNQUSTNRRSPNSRESULT_PK ON COMTNQUSTNRRSPNSRESULT
(
	QUSTNR_RSPNS_RESULT_ID,
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_TMPLAT_ID
)
;
CREATE INDEX COMTNQUSTNRRSPNSRESULT_i01 ON COMTNQUSTNRRSPNSRESULT
(
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_TMPLAT_ID
)
;



CREATE TABLE COMTNQUSTNRIEM
(
	QUSTNR_TMPLAT_ID      CHAR(20) NOT NULL,
	QESTNR_ID             CHAR(20) NOT NULL,
	QUSTNR_QESITM_ID      CHAR(20) NOT NULL,
	QUSTNR_IEM_ID         VARCHAR(20) NOT NULL,
	IEM_SN                NUMERIC(5) NULL,
	IEM_CN                VARCHAR(1000) NULL,
	ETC_ANSWER_AT         CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
	FOREIGN KEY COMTNQUSTNRIEM_FK1 (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRQESITM(QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
)
;

CREATE UNIQUE INDEX COMTNQUSTNRIEM_PK ON COMTNQUSTNRIEM
(
	QUSTNR_TMPLAT_ID,
	QESTNR_ID,
	QUSTNR_QESITM_ID,
	QUSTNR_IEM_ID
)
;
CREATE INDEX COMTNQUSTNRIEM_i01 ON COMTNQUSTNRIEM
(
	QUSTNR_QESITM_ID,
	QESTNR_ID,
	QUSTNR_TMPLAT_ID
)
;



CREATE TABLE COMTNONLINEPOLLMANAGE
(
	POLL_ID               CHAR(20) NOT NULL,
	POLL_NM               VARCHAR(255) NULL,
	POLL_BGNDE            CHAR(10) NULL,
	POLL_ENDDE            CHAR(10) NULL,
	POLL_KND              CHAR(3) NULL,
	POLL_DSUSE_ENNC       CHAR(1) NULL,
	POLL_ATMC_DSUSE_ENNC  CHAR(1) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	 PRIMARY KEY (POLL_ID)
)
;

CREATE UNIQUE INDEX COMTNONLINEPOLLMANAGE_PK ON COMTNONLINEPOLLMANAGE
(
	POLL_ID
)
;



CREATE TABLE COMTNONLINEPOLLIEM
(
	POLL_IEM_NM           VARCHAR(255) NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	POLL_IEM_ID           CHAR(20) NOT NULL,
	POLL_ID               CHAR(20) NOT NULL,
	 PRIMARY KEY (POLL_ID,POLL_IEM_ID),
	FOREIGN KEY COMTNONLINEPOLLIEM_FK1 (POLL_ID) REFERENCES COMTNONLINEPOLLMANAGE(POLL_ID)
)
;

CREATE UNIQUE INDEX COMTNONLINEPOLLIEM_PK ON COMTNONLINEPOLLIEM
(
	POLL_ID,
	POLL_IEM_ID
)
;
CREATE INDEX COMTNONLINEPOLLIEM_i01 ON COMTNONLINEPOLLIEM
(
	POLL_ID
)
;



CREATE TABLE COMTNONLINEPOLLRESULT
(
	POLL_RESULT_ID        CHAR(20) NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	POLL_IEM_ID           CHAR(20) NOT NULL,
	POLL_ID               CHAR(20) NOT NULL,
	 PRIMARY KEY (POLL_RESULT_ID,POLL_IEM_ID,POLL_ID),
	FOREIGN KEY COMTNONLINEPOLLRESULT_FK1 (POLL_ID,POLL_IEM_ID) REFERENCES COMTNONLINEPOLLIEM(POLL_ID,POLL_IEM_ID)
)
;

CREATE UNIQUE INDEX COMTNONLINEPOLLRESULT_PK ON COMTNONLINEPOLLRESULT
(
	POLL_RESULT_ID,
	POLL_IEM_ID,
	POLL_ID
)
;
CREATE INDEX COMTNONLINEPOLLRESULT_i01 ON COMTNONLINEPOLLRESULT
(
	POLL_IEM_ID,
	POLL_ID
)
;



CREATE TABLE COMTNNEWSINFO
(
	NEWS_ID               CHAR(20) NOT NULL,
	NEWS_SJ               VARCHAR(100) NULL,
	NEWS_CN               VARCHAR(2500) NULL,
	NEWS_ORIGIN           VARCHAR(250) NULL,
	NTCE_AT               CHAR(1) NULL,
	FRST_REGIST_PNTTM     DATETIME NOT NULL,
	FRST_REGISTER_ID      VARCHAR(20) NOT NULL,
	LAST_UPDT_PNTTM       DATETIME NOT NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NOT NULL,
	NTCE_DE               CHAR(20) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	 PRIMARY KEY (NEWS_ID),
	FOREIGN KEY COMTNNEWSINFO_FK1 (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
		ON DELETE SET NULL
)
;

CREATE UNIQUE INDEX COMTNNEWSINFO_PK ON COMTNNEWSINFO
(
	NEWS_ID
)
;
CREATE INDEX COMTNNEWSINFO_i01 ON COMTNNEWSINFO
(
	ATCH_FILE_ID
)
;



CREATE TABLE COMTNEVENTINFO
(
	EVENT_ID              CHAR(20) NOT NULL,
	BSNS_YEAR             CHAR(4) NULL,
	BSNS_CODE             VARCHAR(2) NULL,
	EVENT_CN              VARCHAR(1000) NULL,
	EVENT_SVC_BGNDE       CHAR(20) NULL,
	SVC_USE_NMPR_CO       NUMERIC(10) NULL,
	CHARGER_NM            VARCHAR(50) NULL,
	PRPARETG_CN           VARCHAR(2500) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	EVENT_SVC_ENDDE       CHAR(20) NULL,
	EVENT_TY_CODE         CHAR(1) NULL,
	EVENT_CONFM_AT        CHAR(1) NULL,
	EVENT_CONFM_DE        CHAR(20) NULL,
	 PRIMARY KEY (EVENT_ID)
)
;

CREATE UNIQUE INDEX COMTNEVENTINFO_PK ON COMTNEVENTINFO
(
	EVENT_ID
)
;



CREATE TABLE COMTNEXTRLHRINFO
(
	EVENT_ID              CHAR(20) NOT NULL,
	EXTRL_HR_ID           CHAR(20) NOT NULL,
	SEXDSTN_CODE          CHAR(1) NULL,
	EXTRL_HR_NM           VARCHAR(60) NULL,
	OCCP_TY_CODE          CHAR(1) NULL,
	PSITN_INSTT_NM        VARCHAR(100) NULL,
	BRTHDY                CHAR(20) NULL,
	AREA_NO               VARCHAR(4) NULL,
	MIDDLE_TELNO          VARCHAR(4) NULL,
	END_TELNO             VARCHAR(4) NULL,
	EMAIL_ADRES           VARCHAR(50) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (EVENT_ID,EXTRL_HR_ID),
	FOREIGN KEY COMTNEXTRLHRINFO_FK1 (EVENT_ID) REFERENCES COMTNEVENTINFO(EVENT_ID)
)
;

CREATE UNIQUE INDEX COMTNEXTRLHRINFO_PK ON COMTNEXTRLHRINFO
(
	EVENT_ID,
	EXTRL_HR_ID
)
;
CREATE INDEX COMTNEXTRLHRINFO_i01 ON COMTNEXTRLHRINFO
(
	EVENT_ID
)
;



CREATE TABLE COMTCZIP
(
	ZIP                   VARCHAR(6) NOT NULL,
	SN                    NUMERIC(10) NOT NULL,
	CTPRVN_NM             VARCHAR(20) NULL,
	SIGNGU_NM             VARCHAR(20) NULL,
	EMD_NM                VARCHAR(60) NULL,
	LI_BULD_NM            VARCHAR(60) NULL,
	LNBR_DONG_HO          VARCHAR(20) NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (ZIP,SN)
)
;

CREATE UNIQUE INDEX COMTCZIP_PK ON COMTCZIP
(
	ZIP,
	SN
)
;



CREATE TABLE COMTRDNMADRZIP
(
	RDMN_CODE             VARCHAR(12) NOT NULL,
	SN                    NUMERIC(10) NOT NULL,
	CTPRVN_NM             VARCHAR(20) NULL,
	SIGNGU_NM             VARCHAR(20) NULL,
	RDMN                  VARCHAR(60) NULL,
	BDNBR_MNNM            VARCHAR(5) NULL,
	BDNBR_SLNO            VARCHAR(5) NULL,
	BULD_NM               VARCHAR(60) NULL,
	DETAIL_BULD_NM        VARCHAR(60) NULL,
	ZIP                   VARCHAR(6) NOT NULL,
	FRST_REGIST_PNTTM     DATETIME NULL,
	FRST_REGISTER_ID      VARCHAR(20) NULL,
	LAST_UPDT_PNTTM       DATETIME NULL,
	LAST_UPDUSR_ID        VARCHAR(20) NULL,
	 PRIMARY KEY (SN)
)
;

CREATE UNIQUE INDEX COMTRDNMADRZIP_PK ON COMTRDNMADRZIP
(
	RDMN_CODE,
	SN
)
;



CREATE TABLE COMTNBKMKMENUMANAGERESULT
(
	MENU_ID               NUMERIC(20) NOT NULL,
	EMPLYR_ID             VARCHAR(20) NOT NULL,
	MENU_NM               VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH      VARCHAR(100) NOT NULL,
	 PRIMARY KEY (MENU_ID,EMPLYR_ID)
)
;

CREATE UNIQUE INDEX COMTNBKMKMENUMANAGERESULT_PK ON COMTNBKMKMENUMANAGERESULT
(
	MENU_ID,
	EMPLYR_ID
)
;



CREATE TABLE COMTNEMPLYRSCRTYESTBS
(
	SCRTY_DTRMN_TRGET_ID  VARCHAR(20) NOT NULL,
	MBER_TY_CODE          CHAR(5) NULL,
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	 PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
)
;

CREATE UNIQUE INDEX COMTNEMPLYRSCRTYESTBS_PK ON COMTNEMPLYRSCRTYESTBS
(
	SCRTY_DTRMN_TRGET_ID
)
;
CREATE INDEX COMTNEMPLYRSCRTYESTBS_i04 ON COMTNEMPLYRSCRTYESTBS
(
	AUTHOR_CODE
)
;



CREATE TABLE COMTNSITEMAP
(
	MAPNG_CREAT_ID        VARCHAR(30) NOT NULL,
	CREATR_ID             VARCHAR(20) NOT NULL,
	MAPNG_FILE_NM         VARCHAR(60) NOT NULL,
	MAPNG_FILE_PATH       VARCHAR(100) NOT NULL,
	 PRIMARY KEY (MAPNG_CREAT_ID)
)
;

CREATE UNIQUE INDEX COMTNSITEMAP_PK ON COMTNSITEMAP
(
	MAPNG_CREAT_ID
)
;





CREATE TABLE COMTNROLES_HIERARCHY
(
	PARNTS_ROLE           VARCHAR(30) NOT NULL,
	CHLDRN_ROLE           VARCHAR(30) NOT NULL,
	 PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
	FOREIGN KEY COMTNROLES_HIERARCHY_FK1 (PARNTS_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNROLES_HIERARCHY_FK2 (CHLDRN_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
		ON DELETE CASCADE
)
;



CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_PK ON COMTNROLES_HIERARCHY
(
	PARNTS_ROLE,
	CHLDRN_ROLE
)
;



CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_i01 ON COMTNROLES_HIERARCHY
(
	PARNTS_ROLE
)
;



CREATE TABLE COMTNPROGRMLIST
(
	PROGRM_FILE_NM        VARCHAR(60) NOT NULL,
	PROGRM_STRE_PATH      VARCHAR(100) NOT NULL,
	PROGRM_KOREAN_NM      VARCHAR(60) NULL,
	PROGRM_DC             VARCHAR(200) NULL,
	URL                   VARCHAR(100) NOT NULL,
	 PRIMARY KEY (PROGRM_FILE_NM)
)
;

CREATE UNIQUE INDEX COMTNPROGRMLIST_PK ON COMTNPROGRMLIST
(
	PROGRM_FILE_NM
)
;



CREATE TABLE COMTHPROGRMCHANGEDTLS
(
	PROGRM_FILE_NM        VARCHAR(60) NOT NULL,
	REQUST_NO             NUMERIC(10) NOT NULL,
	RQESTER_ID            VARCHAR(20) NOT NULL,
	CHANGE_REQUST_CN      VARCHAR(1000) NULL,
	REQUST_PROCESS_CN     MEDIUMTEXT NULL,
	OPETR_ID              VARCHAR(20) NULL,
	PROCESS_STTUS_CODE    VARCHAR(15) NOT NULL,
	PROCESS_DE            CHAR(20) NULL,
	RQESTDE               CHAR(20) NULL,
	REQUST_SJ             VARCHAR(60) NOT NULL,
	 PRIMARY KEY (PROGRM_FILE_NM,REQUST_NO),
	FOREIGN KEY COMTHPROGRMCHANGEDTLS_FK1 (PROGRM_FILE_NM) REFERENCES COMTNPROGRMLIST(PROGRM_FILE_NM)
		ON DELETE CASCADE
)
;

CREATE UNIQUE INDEX COMTHPROGRMCHANGEDTLS_PK ON COMTHPROGRMCHANGEDTLS
(
	PROGRM_FILE_NM,
	REQUST_NO
)
;
CREATE INDEX COMTHPROGRMCHANGEDTLS_i01 ON COMTHPROGRMCHANGEDTLS
(
	PROGRM_FILE_NM
)
;



CREATE TABLE COMTNMENUINFO
(
	MENU_NM               VARCHAR(60) NOT NULL,
	PROGRM_FILE_NM        VARCHAR(60) NOT NULL,
	MENU_NO               NUMERIC(20) NOT NULL,
	UPPER_MENU_NO         NUMERIC(20) NULL,
	MENU_ORDR             NUMERIC(5) NOT NULL,
	MENU_DC               VARCHAR(250) NULL,
	RELATE_IMAGE_PATH     VARCHAR(100) NULL,
	RELATE_IMAGE_NM       VARCHAR(60) NULL,
	 PRIMARY KEY (MENU_NO),
	FOREIGN KEY COMTNMENUINFO_FK2 (PROGRM_FILE_NM) REFERENCES COMTNPROGRMLIST(PROGRM_FILE_NM)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNMENUINFO_FK1 (UPPER_MENU_NO) REFERENCES COMTNMENUINFO(MENU_NO)
		ON DELETE CASCADE
)
;

CREATE UNIQUE INDEX COMTNMENUINFO_PK ON COMTNMENUINFO
(
	MENU_NO
)
;
CREATE INDEX COMTNMENUINFO_i02 ON COMTNMENUINFO
(
	UPPER_MENU_NO
)
;



CREATE TABLE COMTNMENUCREATDTLS
(
	MENU_NO               NUMERIC(20) NOT NULL,
	AUTHOR_CODE           VARCHAR(30) NOT NULL,
	MAPNG_CREAT_ID        VARCHAR(30) NULL,
	 PRIMARY KEY (MENU_NO,AUTHOR_CODE),
	FOREIGN KEY COMTNMENUCREATDTLS_FK2 (MENU_NO) REFERENCES COMTNMENUINFO(MENU_NO)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNMENUCREATDTLS_FK3 (MAPNG_CREAT_ID) REFERENCES COMTNSITEMAP(MAPNG_CREAT_ID)
		ON DELETE CASCADE,
	FOREIGN KEY COMTNMENUCREATDTLS_FK1 (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
)
;

CREATE UNIQUE INDEX COMTNMENUCREATDTLS_PK ON COMTNMENUCREATDTLS
(
	MENU_NO,
	AUTHOR_CODE
)
;
CREATE INDEX COMTNMENUCREATDTLS_i02 ON COMTNMENUCREATDTLS
(
	MENU_NO
)
;
CREATE INDEX COMTNMENUCREATDTLS_i03 ON COMTNMENUCREATDTLS
(
	MAPNG_CREAT_ID
)
;
CREATE INDEX COMTNMENUCREATDTLS_i04 ON COMTNMENUCREATDTLS
(
	AUTHOR_CODE
)
;

-- 모바일 신규컴포넌트

/* 실시간 공지 */
CREATE TABLE COMTNREALTIMENOTICE
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	NOTICE_SJ             VARCHAR(256) NULL,
	NOTICE_CN             VARCHAR(2048) NULL,
	RECENT_CODE_ID        VARCHAR(6) NULL,
	RECENT_CODE           VARCHAR(15) NULL,
	NOTICE_BGNDT          DATE NOT NULL,
	NOTICE_ENDDT          DATE NOT NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL
);

ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN NOTICE_SJ NOTICE_SJ VARCHAR(256) NULL COMMENT '공지제목';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN NOTICE_CN NOTICE_CN VARCHAR(2048) NULL COMMENT '공지내용';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN RECENT_CODE_ID RECENT_CODE_ID VARCHAR(6) NULL COMMENT '최신구분코드ID';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN RECENT_CODE RECENT_CODE VARCHAR(15) NULL COMMENT '최신구분코드';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN NOTICE_BGNDT NOTICE_BGNDT DATE NOT NULL COMMENT '공지시작일시';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN NOTICE_ENDDT NOTICE_ENDDT DATE NOT NULL COMMENT '공지종료일시';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNREALTIMENOTICE CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNREALTIMENOTICE
	ADD  PRIMARY KEY (SN);

/* 동기화 서비스 */
CREATE TABLE COMTNSYNC
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	SYNC_SJ               VARCHAR(256) NULL,
	SYNC_CN               VARCHAR(2048) NULL,
	SYNC_DT               DATE NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL
);

ALTER TABLE COMTNSYNC CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNSYNC CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNSYNC CHANGE COLUMN SYNC_SJ SYNC_SJ VARCHAR(256) NULL COMMENT '동기화글제목';
ALTER TABLE COMTNSYNC CHANGE COLUMN SYNC_CN SYNC_CN VARCHAR(2048) NULL COMMENT '동기화글내용';
ALTER TABLE COMTNSYNC CHANGE COLUMN SYNC_DT SYNC_DT DATE NULL COMMENT '동기화일시';
ALTER TABLE COMTNSYNC CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNSYNC CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNSYNC
	ADD  PRIMARY KEY (SN);

/* 오프라인 웹 */
CREATE TABLE COMTNOFFLINEWEB
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	OFFLINE_SJ            VARCHAR(256) NULL,
	OFFLINE_CN            VARCHAR(2048) NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL
);

ALTER TABLE COMTNOFFLINEWEB CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNOFFLINEWEB CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNOFFLINEWEB CHANGE COLUMN OFFLINE_SJ OFFLINE_SJ VARCHAR(256) NULL COMMENT '오프라인제목';
ALTER TABLE COMTNOFFLINEWEB CHANGE COLUMN OFFLINE_CN OFFLINE_CN VARCHAR(2048) NULL COMMENT '오프라인내용';
ALTER TABLE COMTNOFFLINEWEB CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNOFFLINEWEB CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNOFFLINEWEB
	ADD  PRIMARY KEY (SN);

/* 모바일 차트/그래프 */
CREATE TABLE COMTNCHARTGRAPH
(
	SN                    INT(20) NOT NULL,
	MBER_ID             VARCHAR(20) NOT NULL,
	XAXIS                 VARCHAR(20) NULL,
	YAXIS                 INT(6) NULL,
	LGD_NM              VARCHAR(20) NULL,
	CREAT_DT            DATE NOT NULL,
	UPDT_DT              DATE NOT NULL
);

ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN XAXIS XAXIS INT(6) NULL COMMENT 'X축값';
ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN YAXIS YAXIS INT(6) NULL COMMENT 'Y축값';
ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN LGD_NM LGD_NM VARCHAR(20) NULL COMMENT '범례명';
ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNCHARTGRAPH CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNCHARTGRAPH
	ADD  PRIMARY KEY (SN);

/* 모바일 기기식별 */
CREATE TABLE COMTNDEVICE
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	UAGENT_INFO           VARCHAR(1024) NULL,
	BROWSER_CODE_ID       VARCHAR(128) NULL,
	BROWSER_CODE          VARCHAR(15) NULL,
	OS_CODE_ID            VARCHAR(128) NULL,
	OS_CODE               VARCHAR(15) NULL,
	RECENT_CODE_ID        VARCHAR(6) NULL,
	RECENT_CODE           VARCHAR(15) NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL
);

ALTER TABLE COMTNDEVICE CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNDEVICE CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNDEVICE CHANGE COLUMN UAGENT_INFO UAGENT_INFO VARCHAR(1024) NULL COMMENT 'UserAgent정보';
ALTER TABLE COMTNDEVICE CHANGE COLUMN BROWSER_CODE_ID BROWSER_CODE_ID VARCHAR(128) NULL COMMENT '브라우저코드ID';
ALTER TABLE COMTNDEVICE CHANGE COLUMN BROWSER_CODE BROWSER_CODE VARCHAR(15) NULL COMMENT '브라우저코드';
ALTER TABLE COMTNDEVICE CHANGE COLUMN OS_CODE_ID OS_CODE_ID VARCHAR(128) NULL COMMENT '운영체제코드ID';
ALTER TABLE COMTNDEVICE CHANGE COLUMN OS_CODE OS_CODE VARCHAR(15) NULL COMMENT '운영체제코드';
ALTER TABLE COMTNDEVICE CHANGE COLUMN RECENT_CODE_ID RECENT_CODE_ID VARCHAR(6) NULL COMMENT '최신구분코드ID';
ALTER TABLE COMTNDEVICE CHANGE COLUMN RECENT_CODE RECENT_CODE VARCHAR(15) NULL COMMENT '최신구분코드';
ALTER TABLE COMTNDEVICE CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNDEVICE CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNDEVICE
	ADD  PRIMARY KEY (SN);

/* 모바일 사진앨범 */ 
CREATE TABLE COMTNPHOTOALBUM
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	PHOTO_SJ              VARCHAR(256) NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	CREAT_DT             DATE NULL,
	UPDT_DT               DATE NULL
);

ALTER TABLE COMTNPHOTOALBUM CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNPHOTOALBUM CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNPHOTOALBUM CHANGE COLUMN PHOTO_SJ PHOTO_SJ VARCHAR(256) NULL COMMENT '사진제목';
ALTER TABLE COMTNPHOTOALBUM CHANGE COLUMN ATCH_FILE_ID ATCH_FILE_ID CHAR(20) NULL COMMENT '첨부파일ID';
ALTER TABLE COMTNPHOTOALBUM CHANGE COLUMN CREAT_DT CREAT_DT DATE NULL COMMENT '생성일시';
ALTER TABLE COMTNPHOTOALBUM CHANGE COLUMN UPDT_DT UPDT_DT DATE NULL COMMENT '수정일시';

ALTER TABLE COMTNPHOTOALBUM
	ADD  PRIMARY KEY (SN);

/* 멀티미디어 */ 
CREATE TABLE COMTNMLTMD
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	MLTMD_CODE_ID         VARCHAR(6) NULL,
	MLTMD_CODE            VARCHAR(15) NULL,
	MLTMD_SJ              VARCHAR(256) NULL,
	BROWSER_NM            VARCHAR(128) NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL
);

ALTER TABLE COMTNMLTMD CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNMLTMD CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNMLTMD CHANGE COLUMN ATCH_FILE_ID ATCH_FILE_ID CHAR(20) NULL COMMENT '첨부파일ID';
ALTER TABLE COMTNMLTMD CHANGE COLUMN MLTMD_CODE_ID MLTMD_CODE_ID VARCHAR(6) NULL COMMENT '멀티미디어구분코드ID';
ALTER TABLE COMTNMLTMD CHANGE COLUMN MLTMD_CODE MLTMD_CODE VARCHAR(15) NULL COMMENT '멀티미디어구분코드';
ALTER TABLE COMTNMLTMD CHANGE COLUMN MLTMD_SJ MLTMD_SJ VARCHAR(256) NULL COMMENT '멀티미디어제목';
ALTER TABLE COMTNMLTMD CHANGE COLUMN BROWSER_NM BROWSER_NM VARCHAR(128) NULL COMMENT '브라우저명';
ALTER TABLE COMTNMLTMD CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNMLTMD CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNMLTMD
	ADD  PRIMARY KEY (SN);

/* MMS발송이력 */
CREATE TABLE COMTNMMS
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	TRNSMIS_NO            VARCHAR(32) NULL,
	RECPTN_NO             VARCHAR(32) NULL,
	MSSAGE_SJ		VARCHAR(32) NOT NULL,
	MSSAGE_CN		VARCHAR(1000) NULL,
	MSSAGE_ID		VARCHAR(52) NULL,
	RQESTER_RESULT_CODE_ID  VARCHAR(6) NULL,
	RQESTER_RESULT_CODE   VARCHAR(15) NULL,
	TRNSMIS_RESULT_CODE_ID  VARCHAR(6) NULL,
	TRNSMIS_RESULT_CODE   VARCHAR(15) NULL,
	TRNSMIS_DT            DATE NOT NULL,
	TRNSMIS_CONFIRM_DT    DATE NULL
);

ALTER TABLE COMTNMMS CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNMMS CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNMMS CHANGE COLUMN TRNSMIS_NO TRNSMIS_NO VARCHAR(32) NULL COMMENT '송신번호';
ALTER TABLE COMTNMMS CHANGE COLUMN RECPTN_NO RECPTN_NO VARCHAR(32) NULL COMMENT '회신번호';
ALTER TABLE COMTNMMS CHANGE COLUMN MSSAGE_SJ MSSAGE_SJ VARCHAR(32) NOT NULL COMMENT 'MMS제목';
ALTER TABLE COMTNMMS CHANGE COLUMN MSSAGE_CN MSSAGE_CN VARCHAR(1000) NULL COMMENT 'MMS내용';
ALTER TABLE COMTNMMS CHANGE COLUMN MSSAGE_ID MSSAGE_ID VARCHAR(52) NULL COMMENT '메시지ID';
ALTER TABLE COMTNMMS CHANGE COLUMN RQESTER_RESULT_CODE_ID RQESTER_RESULT_CODE_ID VARCHAR(6) NULL COMMENT '요청결과코드ID';
ALTER TABLE COMTNMMS CHANGE COLUMN RQESTER_RESULT_CODE RQESTER_RESULT_CODE VARCHAR(15) NULL COMMENT '요청결과코드';
ALTER TABLE COMTNMMS CHANGE COLUMN TRNSMIS_RESULT_CODE_ID TRNSMIS_RESULT_CODE_ID VARCHAR(6) NULL COMMENT '전송결과코드ID';
ALTER TABLE COMTNMMS CHANGE COLUMN TRNSMIS_RESULT_CODE TRNSMIS_RESULT_CODE VARCHAR(15) NULL COMMENT '전송결과코드';
ALTER TABLE COMTNMMS CHANGE COLUMN TRNSMIS_DT TRNSMIS_DT DATE NOT NULL COMMENT '전송일시';
ALTER TABLE COMTNMMS CHANGE COLUMN TRNSMIS_CONFIRM_DT TRNSMIS_CONFIRM_DT DATE NULL COMMENT '전송확인일시';

ALTER TABLE COMTNMMS
	ADD  PRIMARY KEY (SN);

/* MMS 파일첨부 */
CREATE TABLE COMTNMMSATTACH
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	ATCH_FILE_ID          CHAR(20) NULL,
	MMS_ATCH_FILE_SJ      VARCHAR(256) NULL,
	CREAT_DT             DATE NOT NULL,
	UPDT_DT               DATE NOT NULL
);

ALTER TABLE COMTNMMSATTACH CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNMMSATTACH CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNMMSATTACH CHANGE COLUMN ATCH_FILE_ID ATCH_FILE_ID CHAR(20) NULL COMMENT '첨부파일ID';
ALTER TABLE COMTNMMSATTACH CHANGE COLUMN MMS_ATCH_FILE_SJ MMS_ATCH_FILE_SJ VARCHAR(256) NULL COMMENT '첨부파일제목';
ALTER TABLE COMTNMMSATTACH CHANGE COLUMN CREAT_DT CREAT_DT DATE NOT NULL COMMENT '생성일시';
ALTER TABLE COMTNMMSATTACH CHANGE COLUMN UPDT_DT UPDT_DT DATE NOT NULL COMMENT '수정일시';

ALTER TABLE COMTNMMSATTACH
	ADD  PRIMARY KEY (SN);

/* 위치정보 서비스 */
CREATE TABLE COMTNGEOLOCATION
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	BULD_NM               VARCHAR(60) NULL,
	LA                    VARCHAR(48) NULL,
	LO                    VARCHAR(48) NULL,
	TELNO                 VARCHAR(20) NULL,
	ADRES                 VARCHAR(100) NULL
);

ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN BULD_NM BULD_NM VARCHAR(60) NULL COMMENT '건물명';
ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN LA LA VARCHAR(48) NULL COMMENT '위도';
ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN LO LO VARCHAR(48) NULL COMMENT '경도';
ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN TELNO TELNO VARCHAR(20) NULL COMMENT '전화번호';
ALTER TABLE COMTNGEOLOCATION CHANGE COLUMN ADRES ADRES VARCHAR(100) NULL COMMENT '주소';

ALTER TABLE COMTNGEOLOCATION
	ADD  PRIMARY KEY (SN);

/* OPEN API */
CREATE TABLE COMTNOPENAPI
(
	SN                    INT(20) NOT NULL,
	MBER_ID               VARCHAR(20) NOT NULL,
	OPEN_API_SVC_CODE_ID  VARCHAR(6) NULL,
	OPEN_API_SVC_CODE     VARCHAR(15) NULL,
	OPEN_API_SVC_CN       VARCHAR(4000) NULL,
	OPENAPI_PROVD_INSTT_CODE_ID  VARCHAR(6) NULL,
	OPENAPI_PROVD_INSTT_CODE  VARCHAR(15) NULL,
	COLLECT_DT            DATE NOT NULL
);

ALTER TABLE COMTNOPENAPI CHANGE COLUMN SN SN INT(20) NOT NULL COMMENT '순번';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN MBER_ID MBER_ID VARCHAR(20) NOT NULL COMMENT '회원ID';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN OPEN_API_SVC_CODE_ID OPEN_API_SVC_CODE_ID VARCHAR(6) NULL COMMENT 'OPEN-API서비스구분코드ID';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN OPEN_API_SVC_CODE OPEN_API_SVC_CODE VARCHAR(15) NULL COMMENT 'OPEN-API서비스구분코드';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN OPEN_API_SVC_CN OPEN_API_SVC_CN VARCHAR(4000) NULL COMMENT 'OPEN-API서비스내용';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN OPENAPI_PROVD_INSTT_CODE_ID OPENAPI_PROVD_INSTT_CODE_ID VARCHAR(6) NULL COMMENT 'OPEN-API제공기관코드ID';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN OPENAPI_PROVD_INSTT_CODE OPENAPI_PROVD_INSTT_CODE VARCHAR(15) NULL COMMENT 'OPEN-API제공기관코드';
ALTER TABLE COMTNOPENAPI CHANGE COLUMN COLLECT_DT COLLECT_DT DATE NOT NULL COMMENT '수집일시';

ALTER TABLE COMTNOPENAPI
	ADD  PRIMARY KEY (SN);

CREATE TABLE COMTNMOBILEMENUINFO

(
    MENU_CODE           VARCHAR(20) NOT NULL,
    MENU_NM             VARCHAR(60) NULL,
    MENU_LVL            NUMERIC(5) NULL,
    CNNC_URL            VARCHAR(255) NULL,
    MENU_DC             VARCHAR(250) NULL,
    ACTVTY_AT           CHAR(1) NULL,
    UPPER_MENU_ID       VARCHAR(20) NULL,
    
    FRST_REGIST_PNTTM   DATETIME NULL,
    
    FRST_REGISTER_ID    VARCHAR(20) NULL,
    
    LAST_UPDT_PNTTM     DATETIME NULL,
    
    LAST_UPDUSR_ID      VARCHAR(20) NULL,
     PRIMARY KEY (MENU_CODE)
)
;