CREATE TABLE COMTECOPSEQ
(
	TABLE_NAME            VARCHAR2(20)  NOT NULL ,
	NEXT_ID               NUMBER(30)  NULL ,
CONSTRAINT  COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE COMTCCMMNCLCODE
(
	CL_CODE               CHAR(3)  NOT NULL ,
	CL_CODE_NM            VARCHAR2(60)  NULL ,
	CL_CODE_DC            VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
);

CREATE TABLE COMTCCMMNCODE
(
	CODE_ID               VARCHAR2(6)  NOT NULL ,
	CODE_ID_NM            VARCHAR2(60)  NULL ,
	CODE_ID_DC            VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	CL_CODE               CHAR(3)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
CONSTRAINT  COMTCCMMNCODE_FK1 FOREIGN KEY (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE) ON DELETE SET NULL
);

CREATE INDEX COMTCCMMNCODE_i01 ON COMTCCMMNCODE
(CL_CODE  ASC);

CREATE TABLE COMTCCMMNDETAILCODE
(
	CODE_ID               VARCHAR2(6)  NOT NULL ,
	CODE                  VARCHAR2(15)  NOT NULL ,
	CODE_NM               VARCHAR2(60)  NULL ,
	CODE_DC               VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
CONSTRAINT  COMTCCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
);

CREATE INDEX COMTCCMMNDETAILCODE_i01 ON COMTCCMMNDETAILCODE
(CODE_ID  ASC);

CREATE TABLE COMTNAUTHORGROUPINFO
(
	GROUP_ID              CHAR(20)  NOT NULL ,
	GROUP_NM              VARCHAR2(60)  NOT NULL ,
	GROUP_CREAT_DE        CHAR(20)  NOT NULL ,
	GROUP_DC              VARCHAR2(100)  NULL ,
CONSTRAINT  COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
);

CREATE TABLE COMTNGNRLMBER
(
	MBER_ID               VARCHAR2(20)  NOT NULL ,
	PASSWORD              VARCHAR2(200)  NOT NULL ,
	PASSWORD_HINT         VARCHAR2(100)  NULL ,
	PASSWORD_CNSR         VARCHAR2(100)  NULL ,
	IHIDNUM               VARCHAR2(200)  NULL ,
	MBER_NM               VARCHAR2(50)  NOT NULL ,
	ZIP                   VARCHAR2(6)  NOT NULL ,
	ADRES                 VARCHAR2(100)  NOT NULL ,
	AREA_NO               VARCHAR2(4)  NOT NULL ,
	MBER_STTUS            VARCHAR2(15)  NULL ,
	DETAIL_ADRES          VARCHAR2(100)  NULL ,
	END_TELNO             VARCHAR2(4)  NOT NULL ,
	MBTLNUM               VARCHAR2(20)  NOT NULL ,
	GROUP_ID              CHAR(20)  NULL ,
	MBER_FXNUM            VARCHAR2(20)  NULL ,
	MBER_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NOT NULL ,
	SBSCRB_DE             DATE  NULL ,
	SEXDSTN_CODE          CHAR(1)  NULL ,
	ESNTL_ID              CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID),
CONSTRAINT  COMTNGNRLMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID) ON DELETE CASCADE
);



CREATE INDEX COMTNGNRLMBER_i01 ON COMTNGNRLMBER
(GROUP_ID  ASC);

CREATE TABLE COMTNORGNZTINFO
(
	ORGNZT_ID             CHAR(20)  NOT NULL ,
	ORGNZT_NM             VARCHAR2(20)  NOT NULL ,
	ORGNZT_DC             VARCHAR2(100)  NULL ,
CONSTRAINT  COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
);

CREATE TABLE COMTNEMPLYRINFO
(
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	ORGNZT_ID             CHAR(20)  NULL ,
	USER_NM               VARCHAR2(60)  NOT NULL ,
	PASSWORD              VARCHAR2(200)  NOT NULL ,
	EMPL_NO               VARCHAR2(20)  NULL ,
	IHIDNUM               VARCHAR2(200)  NULL ,
	SEXDSTN_CODE          CHAR(1)  NULL ,
	BRTHDY                CHAR(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	HOUSE_ADRES           VARCHAR2(100)  NOT NULL ,
	PASSWORD_HINT         VARCHAR2(100)  NOT NULL ,
	PASSWORD_CNSR         VARCHAR2(100)  NOT NULL ,
	HOUSE_END_TELNO       VARCHAR2(4)  NOT NULL ,
	AREA_NO               VARCHAR2(4)  NOT NULL ,
	DETAIL_ADRES          VARCHAR2(100)  NULL ,
	ZIP                   VARCHAR2(6)  NOT NULL ,
	OFFM_TELNO            VARCHAR2(20)  NULL ,
	MBTLNUM               VARCHAR2(20)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	OFCPS_NM              VARCHAR2(60)  NULL ,
	HOUSE_MIDDLE_TELNO    VARCHAR2(4)  NOT NULL ,
	GROUP_ID              CHAR(20)  NULL ,
	PSTINST_CODE          CHAR(8)  NULL ,
	EMPLYR_STTUS_CODE     CHAR(1)  NOT NULL ,
	ESNTL_ID              CHAR(20)  NOT NULL ,
	CRTFC_DN_VALUE        VARCHAR2(100)  NULL ,
	SBSCRB_DE             DATE  NULL ,
CONSTRAINT  COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
CONSTRAINT  COMTNEMPLYRINFO_FK2 FOREIGN KEY (ORGNZT_ID) REFERENCES COMTNORGNZTINFO(ORGNZT_ID) ON DELETE CASCADE,
CONSTRAINT  COMTNEMPLYRINFO_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID) ON DELETE CASCADE
);



CREATE INDEX COMTNEMPLYRINFO_i01 ON COMTNEMPLYRINFO
(ORGNZT_ID  ASC);



CREATE INDEX COMTNEMPLYRINFO_i02 ON COMTNEMPLYRINFO
(GROUP_ID  ASC);

CREATE TABLE COMTNENTRPRSMBER
(
	ENTRPRS_MBER_ID       VARCHAR2(20)  NOT NULL ,
	ENTRPRS_SE_CODE       CHAR(8)  NULL ,
	BIZRNO                VARCHAR2(10)  NULL ,
	JURIRNO               VARCHAR2(13)  NULL ,
	CMPNY_NM              VARCHAR2(60)  NOT NULL ,
	CXFC                  VARCHAR2(50)  NULL ,
	ZIP                   VARCHAR2(6)  NOT NULL ,
	ADRES                 VARCHAR2(100)  NOT NULL ,
	ENTRPRS_MIDDLE_TELNO  VARCHAR2(4)  NOT NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	INDUTY_CODE           CHAR(1)  NULL ,
	APPLCNT_NM            VARCHAR2(50)  NOT NULL ,
	APPLCNT_IHIDNUM       VARCHAR2(200)  NULL ,
	SBSCRB_DE             DATE  NULL ,
	ENTRPRS_MBER_STTUS    VARCHAR2(15)  NULL ,
	ENTRPRS_MBER_PASSWORD  VARCHAR2(200)  NULL ,
	ENTRPRS_MBER_PASSWORD_HINT  VARCHAR2(100)  NOT NULL ,
	ENTRPRS_MBER_PASSWORD_CNSR  VARCHAR2(100)  NOT NULL ,
	GROUP_ID              CHAR(20)  NULL ,
	DETAIL_ADRES          VARCHAR2(100)  NULL ,
	ENTRPRS_END_TELNO     VARCHAR2(4)  NOT NULL ,
	AREA_NO               VARCHAR2(4)  NOT NULL ,
	APPLCNT_EMAIL_ADRES   VARCHAR2(50)  NOT NULL ,
	ESNTL_ID              CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
CONSTRAINT  COMTNENTRPRSMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID) ON DELETE CASCADE
);



CREATE INDEX COMTNENTRPRSMBER_i01 ON COMTNENTRPRSMBER
(GROUP_ID  ASC);


CREATE TABLE COMTNFILE
(
	ATCH_FILE_ID          CHAR(20)  NOT NULL ,
	CREAT_DT              DATE  NOT NULL ,
	USE_AT                CHAR(1)  NULL ,
CONSTRAINT  COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
);

CREATE TABLE COMTNFILEDETAIL
(
	ATCH_FILE_ID          CHAR(20)  NOT NULL ,
	FILE_SN               NUMBER(10)  NOT NULL ,
	FILE_STRE_COURS       VARCHAR2(2000)  NOT NULL ,
	STRE_FILE_NM          VARCHAR2(255)  NOT NULL ,
	ORIGNL_FILE_NM        VARCHAR2(255)  NULL ,
	FILE_EXTSN            VARCHAR2(20)  NOT NULL ,
	FILE_CN               CLOB  NULL ,
	FILE_SIZE             NUMBER(8)  NULL ,
CONSTRAINT  COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
CONSTRAINT  COMTNFILEDETAIL_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
);



CREATE INDEX COMTNFILEDETAIL_i01 ON COMTNFILEDETAIL
(ATCH_FILE_ID  ASC);

CREATE TABLE COMTHEMAILDSPTCHMANAGE
(
	MSSAGE_ID             VARCHAR2(20)  NOT NULL ,
	EMAIL_CN              CLOB  NULL ,
	SNDR                  VARCHAR2(50)  NOT NULL ,
	RCVER                 VARCHAR2(50)  NOT NULL ,
	SJ                    VARCHAR2(60)  NOT NULL ,
	SNDNG_RESULT_CODE     CHAR(1)  NULL ,
	DSPTCH_DT             CHAR(20)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
CONSTRAINT  COMTHEMAILDSPTCHMANAGE_PK PRIMARY KEY (MSSAGE_ID),
CONSTRAINT  COMTHEMAILDSPTCHMANAGE_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID) ON DELETE SET NULL
);



CREATE INDEX COMTHEMAILDSPTCHMANAGE_i01 ON COMTHEMAILDSPTCHMANAGE
(SNDR  ASC);



CREATE INDEX COMTHEMAILDSPTCHMANAGE_i02 ON COMTHEMAILDSPTCHMANAGE
(ATCH_FILE_ID  ASC);

CREATE TABLE COMTNTMPLATINFO
(
	TMPLAT_ID             CHAR(20)  NOT NULL ,
	TMPLAT_NM             VARCHAR2(255)  NULL ,
	TMPLAT_COURS          VARCHAR2(2000)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	TMPLAT_SE_CODE        CHAR(6)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
);

CREATE TABLE COMTNRESTDE
(
	RESTDE_NO             NUMBER(6)  NOT NULL ,
	RESTDE                CHAR(8)  NULL ,
	RESTDE_NM             VARCHAR2(60)  NULL ,
	RESTDE_DC             VARCHAR2(200)  NULL ,
	RESTDE_SE_CODE        VARCHAR2(2)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNRESTDE_PK PRIMARY KEY (RESTDE_NO)
);

CREATE  VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNGNRLMBER
	UNION ALL
		SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
		FROM COMTNEMPLYRINFO
	UNION ALL
		SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
		FROM COMTNENTRPRSMBER ORDER BY ESNTL_ID;

CREATE TABLE COMTNBBSMASTER
(
	BBS_ID                CHAR(20)  NOT NULL ,
	BBS_NM                VARCHAR2(255)  NOT NULL ,
	BBS_INTRCN            VARCHAR2(2400)  NULL ,
	BBS_TY_CODE           CHAR(6)  NOT NULL ,
	BBS_ATTRB_CODE        CHAR(6)  NOT NULL ,
	REPLY_POSBL_AT        CHAR(1)  NULL ,
	FILE_ATCH_POSBL_AT    CHAR(1)  NOT NULL ,
	ATCH_POSBL_FILE_NUMBER  NUMBER(2)  NOT NULL ,
	ATCH_POSBL_FILE_SIZE  NUMBER(8)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	TMPLAT_ID             CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
);


CREATE TABLE COMTNBBSUSE
(
	BBS_ID                CHAR(20)  NOT NULL ,
	TRGET_ID              CHAR(20)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	REGIST_SE_CODE        CHAR(6)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
CONSTRAINT  COMTNBBSUSE_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);



CREATE INDEX COMTNBBSUSE_i01 ON COMTNBBSUSE
(BBS_ID  ASC);

CREATE TABLE COMTNBBS
(
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	NTT_NO                NUMBER(20)  NULL ,
	NTT_SJ                VARCHAR2(2000)  NULL ,
	NTT_CN                CLOB  NULL ,
	ANSWER_AT             CHAR(1)  NULL ,
	PARNTSCTT_NO          NUMBER(10)  NULL ,
	ANSWER_LC             NUMBER(8)  NULL ,
	SORT_ORDR             NUMBER(8)  NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	NTCE_BGNDE            CHAR(20)  NULL ,
	NTCE_ENDDE            CHAR(20)  NULL ,
	NTCR_ID               VARCHAR2(20)  NULL ,
	NTCR_NM               VARCHAR2(20)  NULL ,
	PASSWORD              VARCHAR2(200)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
CONSTRAINT  COMTNBBS_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);



CREATE INDEX COMTNBBS_i01 ON COMTNBBS
(BBS_ID  ASC);

CREATE TABLE COMTNCMMNTY
(
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	CMMNTY_NM             VARCHAR2(255)  NOT NULL ,
	CMMNTY_INTRCN         VARCHAR2(2400)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	REGIST_SE_CODE        CHAR(6)  NULL ,
	TMPLAT_ID             CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNCMMNTY_PK PRIMARY KEY (CMMNTY_ID)
);

CREATE TABLE COMTNCLUB
(
	CLB_ID                CHAR(20)  NOT NULL ,
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	CLB_NM                VARCHAR2(255)  NOT NULL ,
	CLB_INTRCN            VARCHAR2(2400)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	REGIST_SE_CODE        CHAR(6)  NULL ,
	TMPLAT_ID             CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNCLUB_PK PRIMARY KEY (CLB_ID,CMMNTY_ID)
);


CREATE TABLE COMTNBBSMASTEROPTN
(
	BBS_ID                CHAR(20)  NOT NULL ,
	ANSWER_AT             CHAR(1)  NOT NULL ,
	STSFDG_AT             CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
);

CREATE TABLE COMTNCOMMENT
(
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	ANSWER_NO             NUMBER(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	ANSWER                VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	PASSWORD              VARCHAR2(200)  NULL ,
CONSTRAINT  COMTNCOMMENT_PK PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
CONSTRAINT  COMTNCOMMENT_FK1 FOREIGN KEY (NTT_ID,BBS_ID) REFERENCES COMTNBBS(NTT_ID,BBS_ID)
);



CREATE INDEX COMTNCOMMENT_i01 ON COMTNCOMMENT
(NTT_ID  ASC,BBS_ID  ASC);

CREATE TABLE COMTNSCRAP
(
	SCRAP_ID              CHAR(20)  NOT NULL ,
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	SCRAP_NM              VARCHAR2(100)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNSCRAP_PK PRIMARY KEY (SCRAP_ID)
);

CREATE TABLE COMTNSTSFDG
(
	STSFDG_NO             NUMBER(20)  NOT NULL ,
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	PASSWORD              VARCHAR2(200)  NULL ,
	STSFDG                NUMBER(1)  NOT NULL ,
	STSFDG_CN             VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNSTSFDG_PK PRIMARY KEY (STSFDG_NO)
);

CREATE TABLE COMTHCONFMHISTORY
(
	CONFM_NO              NUMBER(8)  NOT NULL ,
	CONFM_RQESTER_ID      VARCHAR2(20)  NOT NULL ,
	CONFMER_ID            VARCHAR2(20)  NULL ,
	CONFM_DE              CHAR(20)  NULL ,
	CONFM_TY_CODE         CHAR(4)  NOT NULL ,
	CONFM_STTUS_CODE      CHAR(4)  NOT NULL ,
	OPERT_TY_CODE         CHAR(4)  NULL ,
	OPERT_ID              VARCHAR2(20)  NULL ,
	TRGET_JOB_TY_CODE     CHAR(3)  NULL ,
	TRGET_JOB_ID          CHAR(20)  NULL ,
CONSTRAINT  COMTHCONFMHISTORY_PK PRIMARY KEY (CONFM_NO)
);

CREATE TABLE COMTNCMMNTYUSER
(
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	MNGR_AT               CHAR(1)  NOT NULL ,
	SBSCRB_DE             DATE  NULL ,
	SECSN_DE              CHAR(20)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNCMMNTYUSER_PK PRIMARY KEY (CMMNTY_ID,EMPLYR_ID),
CONSTRAINT  COMTNCMMNTYUSER_FK1 FOREIGN KEY (CMMNTY_ID) REFERENCES COMTNCMMNTY(CMMNTY_ID)
);



CREATE INDEX COMTNCMMNTYUSER_i01 ON COMTNCMMNTYUSER
(CMMNTY_ID  ASC);

CREATE TABLE COMTNCLUBUSER
(
	CLB_ID                CHAR(20)  NOT NULL ,
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	OPRTR_AT              CHAR(1)  NOT NULL ,
	SBSCRB_DE             DATE  NULL ,
	SECSN_DE              CHAR(20)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
CONSTRAINT  COMTNCLUBUSER_PK PRIMARY KEY (CLB_ID,CMMNTY_ID,EMPLYR_ID),
CONSTRAINT  COMTNCLUBUSER_FK1 FOREIGN KEY (CLB_ID,CMMNTY_ID) REFERENCES COMTNCLUB(CLB_ID,CMMNTY_ID)
);



CREATE INDEX COMTNCLUBUSER_i01 ON COMTNCLUBUSER
(CLB_ID  ASC,CMMNTY_ID  ASC);

CREATE TABLE COMTNMTGINFO
(
	MTG_ID                CHAR(20)  NOT NULL ,
	MTG_NM                VARCHAR2(255)  NULL ,
	MTG_MTR_CN            VARCHAR2(1000)  NULL ,
	MTG_SN                NUMBER(10)  NULL ,
	MTG_CO                NUMBER(5)  NULL ,
	MTG_DE                CHAR(20)  NULL ,
	MTG_PLACE             VARCHAR2(255)  NULL ,
	MTG_BEGIN_TM          VARCHAR2(14)  NULL ,
	MTG_END_TM            VARCHAR2(14)  NULL ,
	CLSDR_MTG_AT          CHAR(1)  NULL ,
	READNG_BGNDE          CHAR(20)  NULL ,
	READNG_AT             CHAR(1)  NULL ,
	MTG_RESULT_CN         VARCHAR2(1000)  NULL ,
	MTG_RESULT_ENNC       CHAR(1)  NULL ,
	ETC_MATTER            VARCHAR2(1000)  NULL ,
	MNGT_DEPT_ID          VARCHAR2(20)  NULL ,
	MNAER_ID              VARCHAR2(20)  NULL ,
	MNAER_DEPT_ID         VARCHAR2(20)  NULL ,
	MTG_AT                CHAR(1)  NULL ,
	NONATDRN_CO           NUMBER(10)  NULL ,
	ATDRN_CO              NUMBER(10)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNMTGINFO_PK PRIMARY KEY (MTG_ID)
);

CREATE TABLE COMTNSCHDULINFO
(
	SCHDUL_ID             CHAR(20)  NOT NULL ,
	SCHDUL_SE             CHAR(1)  NULL ,
	SCHDUL_DEPT_ID        VARCHAR2(20)  NULL ,
	SCHDUL_KND_CODE       CHAR(1)  NULL ,
	SCHDUL_BGNDE          CHAR(20)  NULL ,
	SCHDUL_ENDDE          CHAR(20)  NULL ,
	SCHDUL_NM             VARCHAR2(255)  NULL ,
	SCHDUL_CN             VARCHAR2(2500)  NULL ,
	SCHDUL_PLACE          VARCHAR2(255)  NULL ,
	SCHDUL_IPCR_CODE      CHAR(1)  NULL ,
	SCHDUL_CHARGER_ID     VARCHAR2(20)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	REPTIT_SE_CODE        CHAR(1)  NULL ,
CONSTRAINT  COMTNSCHDULINFO_PK PRIMARY KEY (SCHDUL_ID)
);

CREATE TABLE COMTNDIARYINFO
(
	SCHDUL_ID             CHAR(20)  NOT NULL ,
	DIARY_ID              CHAR(20)  NOT NULL ,
	DIARY_PROGRSRT        NUMBER(3)  NULL ,
	DIARY_NM              VARCHAR2(255)  NULL ,
	DRCT_MATTER           VARCHAR2(2500)  NULL ,
	PARTCLR_MATTER        VARCHAR2(2500)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNDIARYINFO_PK PRIMARY KEY (SCHDUL_ID,DIARY_ID),
CONSTRAINT  COMTNDIARYINFO_FK1 FOREIGN KEY (SCHDUL_ID) REFERENCES COMTNSCHDULINFO(SCHDUL_ID)
);



CREATE INDEX COMTNDIARYINFO_i01 ON COMTNDIARYINFO
(SCHDUL_ID  ASC);

CREATE TABLE COMTNINDVDLPGECNTNTS
(
	CNTNTS_ID             VARCHAR2(20)  NOT NULL ,
	CNTNTS_NM             VARCHAR2(100)  NOT NULL ,
	CNTC_URL              VARCHAR2(255)  NOT NULL ,
	CNTNTS_USE_AT         CHAR(1)  NOT NULL ,
	CNTNTS_LINK_URL       VARCHAR2(1000)  NULL ,
	CNTNTS_DC             VARCHAR2(250)  NULL ,
CONSTRAINT  COMTNINDVDLPGECNTNTS_PK PRIMARY KEY (CNTNTS_ID)
);



CREATE TABLE COMTNINDVDLPGEESTBS
(
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	UPEND_IMAGE           VARCHAR2(1024)  NULL ,
	TITLEBAR_COLOR        CHAR(7)  NULL ,
	ALGN_MTHD             CHAR(1)  NULL ,
	ALGN_CO               NUMBER(10)  NULL ,
CONSTRAINT  COMTNINDVDLPGEESTBS_PK PRIMARY KEY (EMPLYR_ID)
);



CREATE TABLE COMTNCNTNTSLIST
(
	CNTNTS_ID             VARCHAR2(20)  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
CONSTRAINT  COMTNCNTNTSLIST_PK PRIMARY KEY (CNTNTS_ID,EMPLYR_ID),
CONSTRAINT  COMTNCNTNTSLIST_FK1 FOREIGN KEY (CNTNTS_ID) REFERENCES COMTNINDVDLPGECNTNTS(CNTNTS_ID),
CONSTRAINT  COMTNCNTNTSLIST_FK2 FOREIGN KEY (EMPLYR_ID) REFERENCES COMTNINDVDLPGEESTBS(EMPLYR_ID)
);



CREATE INDEX COMTNCNTNTSLIST_i01 ON COMTNCNTNTSLIST
(CNTNTS_ID  ASC);



CREATE INDEX COMTNCNTNTSLIST_i02 ON COMTNCNTNTSLIST
(EMPLYR_ID  ASC);

CREATE TABLE COMTNSTPLATINFO
(
	USE_STPLAT_ID         CHAR(20)  NOT NULL ,
	USE_STPLAT_NM         VARCHAR2(100)  NULL ,
	USE_STPLAT_CN         CLOB  NULL ,
	INFO_PROVD_AGRE_CN    CLOB  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNSTPLATINFO_PK PRIMARY KEY (USE_STPLAT_ID)
);



CREATE TABLE COMTNHPCMINFO
(
	HPCM_ID               CHAR(20)  NOT NULL ,
	HPCM_SE_CODE          CHAR(1)  NULL ,
	HPCM_DFN              VARCHAR2(1000)  NULL ,
	HPCM_DC               VARCHAR2(2500)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNHPCMINFO_PK PRIMARY KEY (HPCM_ID)
);

CREATE TABLE COMTNWORDDICARYINFO
(
	WORD_ID               CHAR(20)  NOT NULL ,
	WORD_NM               VARCHAR2(255)  NULL ,
	ENG_NM                VARCHAR2(60)  NULL ,
	WORD_DC               VARCHAR2(4000)  NULL ,
	SYNONM                VARCHAR2(100)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNWORDDICARYINFO_PK PRIMARY KEY (WORD_ID)
);


CREATE TABLE COMTNFAQINFO
(
	FAQ_ID                CHAR(20)  NOT NULL ,
	QESTN_SJ              VARCHAR2(255)  NULL ,
	QESTN_CN              VARCHAR2(2500)  NULL ,
	ANSWER_CN             VARCHAR2(2500)  NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	QNA_PROCESS_STTUS_CODE  CHAR(1)  NULL ,
CONSTRAINT  COMTNFAQINFO_PK PRIMARY KEY (FAQ_ID),
CONSTRAINT  COMTNFAQINFO_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID) ON DELETE SET NULL
);



CREATE INDEX COMTNFAQINFO_i01 ON COMTNFAQINFO
(ATCH_FILE_ID  ASC);

CREATE TABLE COMTNQAINFO
(
	QA_ID                 CHAR(20)  NOT NULL ,
	QESTN_SJ              VARCHAR2(255)  NULL ,
	QESTN_CN              VARCHAR2(2500)  NULL ,
	WRITNG_DE             CHAR(20)  NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	QNA_PROCESS_STTUS_CODE  CHAR(1)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	ANSWER_CN             VARCHAR2(2500)  NULL ,
	WRITNG_PASSWORD       VARCHAR2(20)  NULL ,
	ANSWER_DE             CHAR(20)  NULL ,
	EMAIL_ANSWER_AT       CHAR(1)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
CONSTRAINT  COMTNQAINFO_PK PRIMARY KEY (QA_ID)
);


CREATE TABLE COMTNADBKMANAGE
(
	ADBK_ID               CHAR(20)  NOT NULL ,
	ADBK_NM               VARCHAR2(50)  NOT NULL ,
	OTHBC_SCOPE           VARCHAR2(20)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	TRGET_ORGNZT_ID       CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNADBKMANAGE_PK PRIMARY KEY (ADBK_ID)
);

CREATE TABLE COMTNADBK
(
	EMPLYR_ID             VARCHAR2(20) NULL ,
	NCRD_ID               CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	ADBK_CONSTNT_ID       CHAR(20)  NOT NULL ,
	NM                    VARCHAR2(50)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	MBTLNUM               VARCHAR2(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	OFFM_TELNO            VARCHAR2(20)  NULL ,
	HOUSE_TELNO           VARCHAR2(20)  NULL ,
	ADBK_ID               CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNADBK_PK PRIMARY KEY (ADBK_CONSTNT_ID,ADBK_ID),
CONSTRAINT  COMTNADBK_FK1 FOREIGN KEY (ADBK_ID) REFERENCES COMTNADBKMANAGE(ADBK_ID) ON DELETE CASCADE
);

CREATE INDEX COMTNADBK_i01 ON COMTNADBK
(ADBK_ID  ASC);


CREATE TABLE COMTNRECOMENDSITEINFO
(
	RECOMEND_SITE_ID      CHAR(20)  NOT NULL ,
	RECOMEND_SITE_NM      VARCHAR2(100)  NULL ,
	RECOMEND_SITE_URL     VARCHAR2(255)  NULL ,
	RECOMEND_SITE_DC      VARCHAR2(1000)  NULL ,
	RECOMEND_RESN_CN      VARCHAR2(1000)  NULL ,
	RECOMEND_CONFM_AT     CHAR(1)  NULL ,
	CONFM_DE              CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNRECOMENDSITEINFO_PK PRIMARY KEY (RECOMEND_SITE_ID)
);

CREATE TABLE COMTNROLEINFO
(
	ROLE_CODE             VARCHAR2(50)  NOT NULL ,
	ROLE_NM               VARCHAR2(60)  NOT NULL ,
	ROLE_PTTRN            VARCHAR2(300)  NULL ,
	ROLE_DC               VARCHAR2(200)  NULL ,
	ROLE_TY               VARCHAR2(80)  NULL ,
	ROLE_SORT             VARCHAR2(10)  NULL ,
	ROLE_CREAT_DE         CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNROLEINFO_PK PRIMARY KEY (ROLE_CODE)
);

CREATE TABLE COMTNAUTHORINFO
(
	AUTHOR_CODE           VARCHAR2(30)  NOT NULL ,
	AUTHOR_NM             VARCHAR2(60)  NOT NULL ,
	AUTHOR_DC             VARCHAR2(200)  NULL ,
	AUTHOR_CREAT_DE       CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE)
);

CREATE TABLE COMTNAUTHORROLERELATE
(
	AUTHOR_CODE           VARCHAR2(30)  NOT NULL ,
	ROLE_CODE             VARCHAR2(50)  NOT NULL ,
	CREAT_DT              DATE  NULL ,
CONSTRAINT  COMTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
CONSTRAINT  COMTNAUTHORROLERELATE_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE,
CONSTRAINT  COMTNAUTHORROLERELATE_FK2 FOREIGN KEY (ROLE_CODE) REFERENCES COMTNROLEINFO(ROLE_CODE) ON DELETE CASCADE
);



CREATE INDEX COMTNAUTHORROLERELATE_i01 ON COMTNAUTHORROLERELATE
(AUTHOR_CODE  ASC);



CREATE INDEX COMTNAUTHORROLERELATE_i02 ON COMTNAUTHORROLERELATE
(ROLE_CODE  ASC);

CREATE TABLE COMTNADMINISTRATIONWORD
(
	ADMINIST_WORD_ID      CHAR(20)  NOT NULL ,
	ADMINIST_WORD_NM      VARCHAR2(255)  NULL ,
	ADMINIST_WORD_ENG_NM  VARCHAR2(255)  NULL ,
	ADMINIST_WORD_ABRV_NM  VARCHAR2(255)  NULL ,
	THEMA_RELM            VARCHAR2(255)  NULL ,
	WORD_SE               VARCHAR2(255)  NULL ,
	RELATE_STD_WORD       VARCHAR2(255)  NULL ,
	ADMINIST_WORD_DFN     VARCHAR2(2500)  NULL ,
	ADMINIST_WORD_DC      VARCHAR2(4000)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNADMINISTRATIONWORD_PK PRIMARY KEY (ADMINIST_WORD_ID)
);

CREATE TABLE COMTNONLINEMANUAL
(
	ONLINE_MNL_ID         CHAR(20)  NOT NULL ,
	ONLINE_MNL_SE_CODE    CHAR(3)  NULL ,
	ONLINE_MNL_DFN        CLOB  NULL ,
	ONLINE_MNL_DC         CLOB  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	ONLINE_MNL_NM         VARCHAR2(255)  NULL ,
CONSTRAINT  COMTNONLINEMANUAL_PK PRIMARY KEY (ONLINE_MNL_ID)
);

CREATE TABLE COMTNCNSLTLIST
(
	CNSLT_ID              CHAR(20)  NOT NULL ,
	CNSLT_SJ              VARCHAR2(255)  NULL ,
	OTHBC_AT              CHAR(1)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	CNSLT_CN              VARCHAR2(2500)  NULL ,
	MANAGT_CN             VARCHAR2(2500)  NULL ,
	MANAGT_DE             CHAR(20)  NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
	FRST_MBTLNUM          VARCHAR2(4)  NULL ,
	MIDDLE_MBTLNUM        VARCHAR2(4)  NULL ,
	END_MBTLNUM           VARCHAR2(4)  NULL ,
	WRITNG_DE             CHAR(20)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	EMAIL_ANSWER_AT       CHAR(1)  NULL ,
	QNA_PROCESS_STTUS_CODE  CHAR(1)  NULL ,
	WRITNG_PASSWORD       VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNCNSLTLIST_PK PRIMARY KEY (CNSLT_ID)
);

CREATE TABLE COMTNQUSTNRTMPLAT
(
	QUSTNR_TMPLAT_ID      CHAR(20)  NOT NULL ,
	QUSTNR_TMPLAT_TY      VARCHAR2(100)  NULL ,
	QUSTNR_TMPLAT_DC      VARCHAR2(2000)  NULL ,
	QUSTNR_TMPLAT_PATH_NM  VARCHAR2(100)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	QUSTNR_TMPLAT_IMAGE_INFO  BLOB  NULL ,
CONSTRAINT  COMTNQUSTNRTMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
);



CREATE TABLE COMTNQESTNRINFO
(
	QUSTNR_TMPLAT_ID      CHAR(20)  NOT NULL ,
	QESTNR_ID             CHAR(20)  NOT NULL ,
	QUSTNR_SJ             VARCHAR2(255)  NULL ,
	QUSTNR_PURPS          VARCHAR2(1000)  NULL ,
	QUSTNR_WRITNG_GUIDANCE_CN  VARCHAR2(2000)  NULL ,
	QUSTNR_TRGET          VARCHAR2(1000)  NULL ,
	QUSTNR_BGNDE          CHAR(20)  NULL ,
	QUSTNR_ENDDE          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNQESTNRINFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
CONSTRAINT  COMTNQESTNRINFO_FK1 FOREIGN KEY (QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRTMPLAT(QUSTNR_TMPLAT_ID)
);



CREATE INDEX COMTNQESTNRINFO_i01 ON COMTNQESTNRINFO
(QUSTNR_TMPLAT_ID  ASC);



CREATE TABLE COMTNQUSTNRRESPONDINFO
(
	QUSTNR_TMPLAT_ID      CHAR(20)  NOT NULL ,
	QESTNR_ID             CHAR(20)  NOT NULL ,
	QUSTNR_RESPOND_ID     CHAR(20)  NOT NULL ,
	SEXDSTN_CODE          CHAR(1)  NULL ,
	OCCP_TY_CODE          CHAR(1)  NULL ,
	RESPOND_NM            VARCHAR2(50)  NULL ,
	BRTHDY                CHAR(20)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNQUSTNRRESPONDINFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
CONSTRAINT  COMTNQUSTNRRESPONDINFO_FK1 FOREIGN KEY (QUSTNR_TMPLAT_ID,QESTNR_ID) REFERENCES COMTNQESTNRINFO(QUSTNR_TMPLAT_ID,QESTNR_ID)
);



CREATE INDEX COMTNQUSTNRRESPONDINFO_i01 ON COMTNQUSTNRRESPONDINFO
(QESTNR_ID  ASC,QUSTNR_TMPLAT_ID  ASC);

CREATE TABLE COMTNQUSTNRQESITM
(
	QESTNR_ID             CHAR(20)  NOT NULL ,
	QUSTNR_QESITM_ID      CHAR(20)  NOT NULL ,
	QUSTNR_TMPLAT_ID      CHAR(20)  NOT NULL ,
	QESTN_SN              NUMBER(10)  NULL ,
	QESTN_TY_CODE         CHAR(1)  NULL ,
	QESTN_CN              VARCHAR2(2500)  NULL ,
	MXMM_CHOISE_CO        NUMBER(5)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NOT NULL ,
CONSTRAINT  COMTNQUSTNRQESITM_PK PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
CONSTRAINT  COMTNQUSTNRQESITM_FK1 FOREIGN KEY (QUSTNR_TMPLAT_ID,QESTNR_ID) REFERENCES COMTNQESTNRINFO(QUSTNR_TMPLAT_ID,QESTNR_ID)
);



CREATE INDEX COMTNQUSTNRQESITM_i02 ON COMTNQUSTNRQESITM
(QESTNR_ID  ASC,QUSTNR_TMPLAT_ID  ASC);



CREATE TABLE COMTNQUSTNRRSPNSRESULT
(
	QUSTNR_RSPNS_RESULT_ID  CHAR(20)  NOT NULL ,
	QESTNR_ID             CHAR(20)  NOT NULL ,
	QUSTNR_QESITM_ID      CHAR(20)  NOT NULL ,
	QUSTNR_TMPLAT_ID      CHAR(20)  NOT NULL ,
	RESPOND_ANSWER_CN     VARCHAR2(1000)  NULL ,
	ETC_ANSWER_CN         VARCHAR2(1000)  NULL ,
	RESPOND_NM            VARCHAR2(50)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	QUSTNR_IEM_ID         VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNQUSTNRRSPNSRESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
CONSTRAINT  COMTNQUSTNRRSPNSRESULT_FK1 FOREIGN KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRQESITM(QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);



CREATE INDEX COMTNQUSTNRRSPNSRESULT_i01 ON COMTNQUSTNRRSPNSRESULT
(QESTNR_ID  ASC,QUSTNR_QESITM_ID  ASC,QUSTNR_TMPLAT_ID  ASC);

CREATE TABLE COMTNQUSTNRIEM
(
	QUSTNR_TMPLAT_ID      CHAR(20)  NOT NULL ,
	QESTNR_ID             CHAR(20)  NOT NULL ,
	QUSTNR_QESITM_ID      CHAR(20)  NOT NULL ,
	QUSTNR_IEM_ID         VARCHAR2(20)  NOT NULL ,
	IEM_SN                NUMBER(5)  NULL ,
	IEM_CN                VARCHAR2(1000)  NULL ,
	ETC_ANSWER_AT         CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNQUSTNRIEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
CONSTRAINT  COMTNQUSTNRIEM_FK1 FOREIGN KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID) REFERENCES COMTNQUSTNRQESITM(QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);



CREATE INDEX COMTNQUSTNRIEM_i01 ON COMTNQUSTNRIEM
(QUSTNR_QESITM_ID  ASC,QESTNR_ID  ASC,QUSTNR_TMPLAT_ID  ASC);

CREATE TABLE COMTNONLINEPOLLMANAGE
(
	POLL_ID               CHAR(20)  NOT NULL ,
	POLL_NM               VARCHAR2(255)  NULL ,
	POLL_BGNDE            CHAR(10)  NULL ,
	POLL_ENDDE            CHAR(10)  NULL ,
	POLL_KND              CHAR(3)  NULL ,
	POLL_DSUSE_ENNC       CHAR(1)  NULL ,
	POLL_ATMC_DSUSE_ENNC  CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNONLINEPOLLMANAGE_PK PRIMARY KEY (POLL_ID)
);

CREATE TABLE COMTNONLINEPOLLIEM
(
	POLL_IEM_NM           VARCHAR2(255)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	POLL_IEM_ID           CHAR(20)  NOT NULL ,
	POLL_ID               CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNONLINEPOLLIEM_PK PRIMARY KEY (POLL_ID,POLL_IEM_ID),
CONSTRAINT  COMTNONLINEPOLLIEM_FK1 FOREIGN KEY (POLL_ID) REFERENCES COMTNONLINEPOLLMANAGE(POLL_ID)
);



CREATE INDEX COMTNONLINEPOLLIEM_i01 ON COMTNONLINEPOLLIEM
(POLL_ID  ASC);



CREATE TABLE COMTNONLINEPOLLRESULT
(
	POLL_RESULT_ID        CHAR(20)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	POLL_IEM_ID           CHAR(20)  NOT NULL ,
	POLL_ID               CHAR(20)  NOT NULL ,
CONSTRAINT  COMTNONLINEPOLLRESULT_PK PRIMARY KEY (POLL_RESULT_ID,POLL_IEM_ID,POLL_ID),
CONSTRAINT  COMTNONLINEPOLLRESULT_FK1 FOREIGN KEY (POLL_ID,POLL_IEM_ID) REFERENCES COMTNONLINEPOLLIEM(POLL_ID,POLL_IEM_ID)
);



CREATE INDEX COMTNONLINEPOLLRESULT_i01 ON COMTNONLINEPOLLRESULT
(POLL_IEM_ID  ASC,POLL_ID  ASC);


CREATE TABLE COMTNNEWSINFO
(
	NEWS_ID               CHAR(20)  NOT NULL ,
	NEWS_SJ               VARCHAR2(100)  NULL ,
	NEWS_CN               VARCHAR2(2500)  NULL ,
	NEWS_ORIGIN           VARCHAR2(250)  NULL ,
	NTCE_AT               CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NOT NULL ,
	NTCE_DE               CHAR(20)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
CONSTRAINT  COMTNNEWSINFO_PK PRIMARY KEY (NEWS_ID),
CONSTRAINT  COMTNNEWSINFO_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID) ON DELETE CASCADE
);



CREATE INDEX COMTNNEWSINFO_i01 ON COMTNNEWSINFO
(ATCH_FILE_ID  ASC);

CREATE TABLE COMTNEVENTINFO
(
	EVENT_ID              CHAR(20)  NOT NULL ,
	BSNS_YEAR             CHAR(4)  NULL ,
	BSNS_CODE             VARCHAR2(2)  NULL ,
	EVENT_CN              VARCHAR2(1000)  NULL ,
	EVENT_SVC_BGNDE       CHAR(20)  NULL ,
	SVC_USE_NMPR_CO       NUMBER(10)  NULL ,
	CHARGER_NM            VARCHAR2(50)  NULL ,
	PRPARETG_CN           VARCHAR2(2500)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	EVENT_SVC_ENDDE       CHAR(20)  NULL ,
	EVENT_TY_CODE         CHAR(1)  NULL ,
	EVENT_CONFM_AT        CHAR(1)  NULL ,
	EVENT_CONFM_DE        CHAR(20)  NULL ,
CONSTRAINT  COMTNEVENTINFO_PK PRIMARY KEY (EVENT_ID)
);



CREATE TABLE COMTNEXTRLHRINFO
(
	EVENT_ID              CHAR(20)  NOT NULL ,
	EXTRL_HR_ID           CHAR(20)  NOT NULL ,
	SEXDSTN_CODE          CHAR(1)  NULL ,
	EXTRL_HR_NM           VARCHAR2(60)  NULL ,
	OCCP_TY_CODE          CHAR(1)  NULL ,
	PSITN_INSTT_NM        VARCHAR2(100)  NULL ,
	BRTHDY                CHAR(20)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNEXTRLHRINFO_PK PRIMARY KEY (EVENT_ID,EXTRL_HR_ID),
CONSTRAINT  COMTNEXTRLHRINFO_FK1 FOREIGN KEY (EVENT_ID) REFERENCES COMTNEVENTINFO(EVENT_ID)
);



CREATE INDEX COMTNEXTRLHRINFO_i01 ON COMTNEXTRLHRINFO
(EVENT_ID  ASC);

CREATE TABLE COMTCZIP
(
	ZIP                   VARCHAR2(6)  NOT NULL ,
	SN                    NUMBER(10)  NOT NULL ,
	CTPRVN_NM             VARCHAR2(20)  NULL ,
	SIGNGU_NM             VARCHAR2(20)  NULL ,
	EMD_NM                VARCHAR2(60)  NULL ,
	LI_BULD_NM            VARCHAR2(60)  NULL ,
	LNBR_DONG_HO          VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCZIP_PK PRIMARY KEY (ZIP,SN)
);



CREATE TABLE COMTRDNMADRZIP
(
	RDMN_CODE             VARCHAR2(12) NOT NULL,
	SN                    NUMBER(10) NOT NULL,
	CTPRVN_NM             VARCHAR2(20) NULL,
	SIGNGU_NM             VARCHAR2(20) NULL,
	RDMN                  VARCHAR2(60) NULL,
	BDNBR_MNNM            VARCHAR2(5) NULL,
	BDNBR_SLNO            VARCHAR2(5) NULL,
	BULD_NM               VARCHAR2(60) NULL,
	DETAIL_BULD_NM        VARCHAR2(60) NULL,
	ZIP                   VARCHAR2(6) NOT NULL,
	FRST_REGIST_PNTTM     DATE NULL,
	FRST_REGISTER_ID      VARCHAR2(20) NULL,
	LAST_UPDT_PNTTM       DATE NULL,
	LAST_UPDUSR_ID        VARCHAR2(20) NULL,
CONSTRAINT  COMTRDNMADRZIP_PK PRIMARY KEY (SN)
);

CREATE TABLE COMTNBKMKMENUMANAGERESULT
(
	MENU_ID               NUMBER(20)  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	MENU_NM               VARCHAR2(60)  NOT NULL ,
	PROGRM_STRE_PATH      VARCHAR2(100)  NOT NULL ,
CONSTRAINT  COMTNBKMKMENUMANAGERESULT_PK PRIMARY KEY (MENU_ID,EMPLYR_ID)
);

CREATE TABLE COMTNEMPLYRSCRTYESTBS
(
	SCRTY_DTRMN_TRGET_ID  VARCHAR2(20)  NOT NULL ,
	MBER_TY_CODE          CHAR(5)  NULL ,
	AUTHOR_CODE           VARCHAR2(30)  NOT NULL 
);


CREATE INDEX COMTNEMPLYRSCRTYESTBS_i04 ON COMTNEMPLYRSCRTYESTBS
(AUTHOR_CODE  ASC);


CREATE TABLE COMTNSITEMAP
(
	MAPNG_CREAT_ID        VARCHAR2(30)  NOT NULL ,
	CREATR_ID             VARCHAR2(20)  NOT NULL ,
	MAPNG_FILE_NM         VARCHAR2(60)  NOT NULL ,
	MAPNG_FILE_PATH       VARCHAR2(100)  NOT NULL ,
CONSTRAINT  COMTNSITEMAP_PK PRIMARY KEY (MAPNG_CREAT_ID)
);

CREATE TABLE COMTNROLES_HIERARCHY
(
	PARNTS_ROLE           VARCHAR2(30)  NOT NULL ,
	CHLDRN_ROLE           VARCHAR2(30)  NOT NULL ,
CONSTRAINT  COMTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
CONSTRAINT  COMTNROLES_HIERARCHY_FK1 FOREIGN KEY (PARNTS_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE,
CONSTRAINT  COMTNROLES_HIERARCHY_FK2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE) ON DELETE CASCADE
);



CREATE UNIQUE INDEX COMTNROLES_HIERARCHY_i01 ON COMTNROLES_HIERARCHY
(PARNTS_ROLE  ASC);



CREATE INDEX COMTNROLES_HIERARCHY_i02 ON COMTNROLES_HIERARCHY
(CHLDRN_ROLE  ASC);

CREATE TABLE COMTNPROGRMLIST
(
	PROGRM_FILE_NM        VARCHAR2(60)  NOT NULL ,
	PROGRM_STRE_PATH      VARCHAR2(100)  NOT NULL ,
	PROGRM_KOREAN_NM      VARCHAR2(60)  NULL ,
	PROGRM_DC             VARCHAR2(200)  NULL ,
	URL                   VARCHAR2(100)  NOT NULL ,
CONSTRAINT  COMTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM)
);



CREATE TABLE COMTHPROGRMCHANGEDTLS
(
	PROGRM_FILE_NM        VARCHAR2(60)  NOT NULL ,
	REQUST_NO             NUMBER(10)  NOT NULL ,
	RQESTER_ID            VARCHAR2(20)  NOT NULL ,
	CHANGE_REQUST_CN      VARCHAR2(1000)  NULL ,
	REQUST_PROCESS_CN     CLOB  NULL ,
	OPETR_ID              VARCHAR2(20)  NULL ,
	PROCESS_STTUS_CODE    VARCHAR2(15)  NOT NULL ,
	PROCESS_DE            CHAR(20)  NULL ,
	RQESTDE               CHAR(20)  NULL ,
	REQUST_SJ             VARCHAR2(60)  NOT NULL ,
CONSTRAINT  COMTHPROGRMCHANGEDTLS_PK PRIMARY KEY (PROGRM_FILE_NM,REQUST_NO),
CONSTRAINT  COMTHPROGRMCHANGEDTLS_FK1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES COMTNPROGRMLIST(PROGRM_FILE_NM) ON DELETE CASCADE
);



CREATE INDEX COMTHPROGRMCHANGEDTLS_i01 ON COMTHPROGRMCHANGEDTLS
(PROGRM_FILE_NM  ASC);

CREATE TABLE COMTNMENUINFO
(
	MENU_NM               VARCHAR2(60)  NOT NULL ,
	PROGRM_FILE_NM        VARCHAR2(60)  NOT NULL ,
	MENU_NO               NUMBER(20)  NOT NULL ,
	UPPER_MENU_NO         NUMBER(20)  NULL ,
	MENU_ORDR             NUMBER(5)  NOT NULL ,
	MENU_DC               VARCHAR2(250)  NULL ,
	RELATE_IMAGE_PATH     VARCHAR2(100)  NULL ,
	RELATE_IMAGE_NM       VARCHAR2(60)  NULL ,
CONSTRAINT  COMTNMENUINFO_PK PRIMARY KEY (MENU_NO),
CONSTRAINT  COMTNMENUINFO_FK2 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES COMTNPROGRMLIST(PROGRM_FILE_NM) ON DELETE CASCADE,
CONSTRAINT  COMTNMENUINFO_FK1 FOREIGN KEY (UPPER_MENU_NO) REFERENCES COMTNMENUINFO(MENU_NO) ON DELETE CASCADE
);






CREATE INDEX COMTNMENUINFO_i02 ON COMTNMENUINFO
(UPPER_MENU_NO  ASC);


CREATE TABLE COMTNMENUCREATDTLS
(
	MENU_NO               NUMBER(20)  NOT NULL ,
	AUTHOR_CODE           VARCHAR2(30)  NOT NULL ,
	MAPNG_CREAT_ID        VARCHAR2(30)  NULL ,
CONSTRAINT  COMTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
CONSTRAINT  COMTNMENUCREATDTLS_FK2 FOREIGN KEY (MENU_NO) REFERENCES COMTNMENUINFO(MENU_NO) ON DELETE CASCADE,
CONSTRAINT  COMTNMENUCREATDTLS_FK3 FOREIGN KEY (MAPNG_CREAT_ID) REFERENCES COMTNSITEMAP(MAPNG_CREAT_ID) ON DELETE CASCADE,
CONSTRAINT  COMTNMENUCREATDTLS_FK1 FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
);



CREATE INDEX COMTNMENUCREATDTLS_i02 ON COMTNMENUCREATDTLS
(MENU_NO  ASC);



CREATE INDEX COMTNMENUCREATDTLS_i03 ON COMTNMENUCREATDTLS
(MAPNG_CREAT_ID  ASC);



CREATE INDEX COMTNMENUCREATDTLS_i04 ON COMTNMENUCREATDTLS
(AUTHOR_CODE  ASC);

-- 모바일 신규컴포넌트

CREATE TABLE COMTNREALTIMENOTICE
 (
	SN					NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID				VARCHAR2(20 BYTE) NOT NULL ENABLE,
    NOTICE_SJ			VARCHAR2(256 BYTE),
    NOTICE_CN			VARCHAR2(2048 BYTE),
    RECENT_CODE_ID		VARCHAR2(6 BYTE),
    RECENT_CODE			VARCHAR2(15 BYTE),
    NOTICE_BGNDT		DATE NOT NULL ENABLE,
    NOTICE_ENDDT		DATE NOT NULL ENABLE,
    CREAT_DT			DATE NOT NULL ENABLE,
    UPDT_DT				DATE NOT NULL ENABLE,
CONSTRAINT  COMTNREALTIMENOTICE_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNSYNC
  (
    SN			NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID		VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SYNC_SJ		VARCHAR2(256 BYTE),
    SYNC_CN		VARCHAR2(2048 BYTE),
    SYNC_DT		DATE,
    CREAT_DT	DATE NOT NULL ENABLE,
    UPDT_DT		DATE NOT NULL ENABLE,
CONSTRAINT  COMTNSYNC_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNOFFLINEWEB
  (
    SN			NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID		VARCHAR2(20 BYTE) NOT NULL ENABLE,
    OFFLINE_SJ	VARCHAR2(256 BYTE),
    OFFLINE_CN	VARCHAR2(2048 BYTE),
    CREAT_DT	DATE NOT NULL ENABLE,
    UPDT_DT		DATE NOT NULL ENABLE,
CONSTRAINT  COMTNOFFLINEWEB_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNCHARTGRAPH
  (
    SN				NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID			VARCHAR2(20 BYTE) NOT NULL ENABLE,
    XAXIS			VARCHAR2(20 BYTE),
    YAXIS			NUMBER(6,0),
    LGD_NM			VARCHAR2(20 BYTE),
    CREAT_DT		DATE NOT NULL ENABLE,
    UPDT_DT			DATE NOT NULL ENABLE,
CONSTRAINT  COMTNCHARTGRAPH_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNDEVICE
  (
    SN					NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID				VARCHAR2(20 BYTE) NOT NULL ENABLE,
    UAGENT_INFO			VARCHAR2(1024 BYTE),
    BROWSER_CODE_ID		VARCHAR2(6 BYTE),
    BROWSER_CODE		VARCHAR2(15 BYTE),
    OS_CODE_ID			VARCHAR2(6 BYTE),
    OS_CODE				VARCHAR2(15 BYTE),
    RECENT_CODE_ID		VARCHAR2(6 BYTE),
    RECENT_CODE			VARCHAR2(15 BYTE),
    CREAT_DT			DATE NOT NULL ENABLE,
    UPDT_DT				DATE NOT NULL ENABLE,
CONSTRAINT  COMTNDEVICE_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNPHOTOALBUM
  (
    SN				NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID			VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PHOTO_SJ		VARCHAR2(256 BYTE) NULL,
    ATCH_FILE_ID	CHAR(20 BYTE) NULL,
    CREAT_DT		DATE,
    UPDT_DT			DATE,
CONSTRAINT  COMTNPHOTOALBUM_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNMLTMD
  (
    SN					NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID				VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ATCH_FILE_ID		CHAR(20 BYTE),
    MLTMD_CODE_ID		VARCHAR2(6 BYTE),
    MLTMD_CODE			VARCHAR2(15 BYTE),
    MLTMD_SJ			VARCHAR2(256 BYTE),
    BROWSER_NM			VARCHAR2(128 BYTE),
    CREAT_DT			DATE NOT NULL ENABLE,
    UPDT_DT				DATE NOT NULL ENABLE,
CONSTRAINT  COMTNMLTMD_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNMMS
  (
    SN                     	NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID                	VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TRNSMIS_NO             	VARCHAR2(32 BYTE),
    RECPTN_NO              	VARCHAR2(32 BYTE),
    MSSAGE_SJ				VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MSSAGE_CN				VARCHAR2(1000 BYTE),
    MSSAGE_ID				VARCHAR2(52 BYTE),
    RQESTER_RESULT_CODE_ID 	VARCHAR2(6 BYTE),
    RQESTER_RESULT_CODE    	VARCHAR2(15 BYTE),
    TRNSMIS_RESULT_CODE_ID 	VARCHAR2(6 BYTE),
    TRNSMIS_RESULT_CODE    	VARCHAR2(15 BYTE),
    TRNSMIS_DT 				DATE NOT NULL ENABLE,
    TRNSMIS_CONFIRM_DT 		DATE,
CONSTRAINT  COMTNMMS_PK PRIMARY KEY (SN)
  );
  
  
CREATE TABLE COMTNMMSATTACH
  (
    SN					NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID				VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ATCH_FILE_ID		CHAR(20 BYTE),
    MMS_ATCH_FILE_SJ	VARCHAR2(256 BYTE),
    CREAT_DT			DATE NOT NULL ENABLE,
    UPDT_DT				DATE NOT NULL ENABLE,
CONSTRAINT  COMTNMMSATTACH_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNGEOLOCATION
  (
	SN				NUMBER(20,0) NOT NULL ENABLE,
	MBER_ID			VARCHAR2(20 BYTE) NOT NULL ENABLE,
    BULD_NM			VARCHAR2(60 BYTE) NOT NULL ENABLE,
    LA				VARCHAR2(48 BYTE),
    LO				VARCHAR2(48 BYTE),
    TELNO			VARCHAR2(20 BYTE),
    ADRES			VARCHAR2(100 BYTE),
CONSTRAINT  COMTNGEOLOCATION_PK PRIMARY KEY (SN)
  );
  
CREATE TABLE COMTNOPENAPI
  (
    SN								NUMBER(20,0) NOT NULL ENABLE,
    MBER_ID							VARCHAR2(20 BYTE) NOT NULL ENABLE,
    OPEN_API_SVC_CODE_ID			VARCHAR2(6 BYTE) NULL,
    OPEN_API_SVC_CODE				VARCHAR2(15 BYTE) NULL,
    OPEN_API_SVC_CN					VARCHAR2(4000 BYTE) NULL,
    OPENAPI_PROVD_INSTT_CODE_ID		VARCHAR2(6 BYTE) NULL,
    OPENAPI_PROVD_INSTT_CODE		VARCHAR2(15 BYTE) NULL,
    COLLECT_DT						DATE NOT NULL ENABLE,
CONSTRAINT  COMTNOPENAPI_PK PRIMARY KEY (SN)
  );
  
  CREATE TABLE COMTNMOBILEMENUINFO

(
    MENU_CODE           VARCHAR(20) NOT NULL,
    MENU_NM             VARCHAR(60) NULL,
    MENU_LVL            NUMBER(5) NULL,
    CNNC_URL            VARCHAR(255) NULL,
    MENU_DC             VARCHAR(250) NULL,
    ACTVTY_AT           CHAR(1) NULL,
    UPPER_MENU_ID       VARCHAR(20) NULL,
    
    FRST_REGIST_PNTTM   DATE NULL,
    
    FRST_REGISTER_ID    VARCHAR(20) NULL,
    
    LAST_UPDT_PNTTM     DATE NULL,
    
    LAST_UPDUSR_ID      VARCHAR(20) NULL,
     PRIMARY KEY (MENU_CODE)
)
;